Refactor/map field
YesWiki/yeswiki pull request #1072
Opened 2023-05-04 18:17 UTC by J9rem

cette macro a pour objectif de tenir compte d'une partie des propositions de VeVeQNV dans la branche 
https://github.com/VeveQNV/yeswiki/tree/geolocation-refactor

L'idée est de faire un refactor du champ carte pour le rendre plus facile à améliorer.
Au passage, la recherche prend maintenant en compte les champs `town` `street` ... pour avoir une recherche plus fine
Il y a aussi prise en compte des arrondissements pour les codes postaux lors de l'auto-complétion

**Ce que ça fait**:
 - réécriture du champ `MapField`
 - réécriture du système d'appel asynchrone pour les url 
 - adaptation des fichiers de langues
 - adaptation des templates `twig` pour relier au nouveau fichier `javascript` et au nouveau format des données
 - ajout de nouvelles options dans le constructeurs graphiques de formulaire pour le champ `map` **particularité** : ces options sont stockées dans une seule propriété du champ, séparée par le caractère `|`

**Pour tester**:
 - se rendre dans le constructeur graphique de formulaire et tester les différentes options disponibles pour le champ `map`
 - modifier une fiche avec un champ `map` et tester les différentes localisation possibles

_Il semblerait maintenant possible de mettre plusieurs champs `map` dans la même fiche, mais pas testé (en prenant soin que chaque champ `map` fasse respectivement référence à des noms de champs différents `bf_latitude` `bf_latitude1`_

2023-05-05 09:18 UTC, seballot requested changes
coucou !

Merci Jerem pour la PR !

@mrflos concernant nominatim, cette PR utilise data.gouv pour l'autocompletion, nominatim est utilisé pour la recherche standard, donc  data.gouv si autorise des requetes d'autocomplétion c'est niquel (mais j'ai pas vérifié, @J9rem  tu en sais plus?)

Avant de regarder plus en détail le code, pour moi y'a des trucs qui ne marchent pas en tant qu'utilisateur

### Autocomplete ne fonctionne pas
Je crée un champ ville
![image](https://user-images.githubusercontent.com/17404254/236417711-6d29308f-0347-4607-95e7-eb5635824911.png)

Je configure dans le champ map l'autocompletion
![image](https://user-images.githubusercontent.com/17404254/236417748-533f68c9-c9ae-44aa-b6d5-7c6b641c1882.png)

Mais dans le formulaire rien ne se passe, pour info le fichier javascript `map-field-autocomplete` n'est pas chargé

J'ai loupé un truc dans la config?

### Le geocodage marche super mal
C'était peut être déjà le cas avant, mais j'ai fait deux tests 
1. Je crée un champs "bf_adresse" générique, je rentre dedans "Labrit" (mon village), j'arrive je ne sais ou dans le monde. D'après ce que je comprend, le bf_address est assimulé à une streetAddress, mais c'est pas très intuitif. Moi je pensais que c'était juste un champ adresse générale ou je met ce que je veux
2. Je crée un champ "ville", je l'assigne comme champ pour champ ville dans le field map, je met "Labrit" et je geocalise, j'arrive en France mais pas du tout dans mon village...
Pourtant une requete toute simple nominatim trouve parfaitement mon village : https://nominatim.openstreetmap.org/search?q=Labrit. Je pense que le problème est que tu utilise "town" alors qu'il faut utiliser "city" :  https://nominatim.openstreetmap.org/search?city=labrit   https://nominatim.openstreetmap.org/search?town=labrit . Mais je sais pas dans quel cas if faut utiliser town. Perso je pense que c'est plus simple de concatener les champs qu'on a pour créer une string en l'envoyer en recherche générale dans nominatim, i.e `search?q="40420 Labrit"` plutot que `search?town=Labrit&postcode=40420`

### L'implémentation ne marche qu'avec la France
d'après ce que je comprend, ce n'est sensé marché que pour la France tout ça. Du coup c'est quoi le plan pour les autres pays? genre nos amis belge ah ah Faudrait au moins que ça soit dit quelque part non?

### address1 address2
Pas sur que ça soit nécessaire, ça alourdit l'interface, mais à voir avec les utilisateurs
![image](https://user-images.githubusercontent.com/17404254/236418520-2e1e4fbf-b906-42f5-9c52-572d60bf245f.png)

### Message d'erreur
petit message d'erreur pas très user friendly si je laisse mon champ ville vide

![image](https://user-images.githubusercontent.com/17404254/236415160-213d6154-83a6-4e5b-a758-d0e138d7fd6b.png)

### révision plus générale de ce champ map
Bon ça demanderai beaucoup plus de boulot et de réflexion, mais perso je pense que ce champ Map n'est pas bien fichu depuis le début. le fait qu'il ne soit pas directement associé à des champ pour rentrer l'adresse c'est franchement bizarre. Mais bon faudrait en discuter de vive voix, et ce n'est pas le sujet de cette PR !

2023-05-05 14:16 UTC, J9rem commented
Merci @seballot pour cette revue en si peu de temps. En plus, tu as fait une analyse fine et constructive.

**Réponses**
 - **autocomplétion** : 
   - l'objet `geoloationHelper` utilise bien le service https://geo.api.gouv.fr/ (cf. https://github.com/YesWiki/yeswiki/blob/8fdd459e061d84190086c36439e51f9c98d81a2a/tools/bazar/presentation/javascripts/geolocationHelper.js#L554)
   - je n'ai fait que réécrire l'appel sur cette api pour utiliser des `fetch` et temporiser 100 ms entre deux requêtes successives (pour éviter d'être bloqué) mais c'est l'api utilisée depuis 3-4 anec par YesWiki, je n'ai rien changé sur ce point, donc normalement ça devrait bien fonctionner
   - effectivement, la géolocalisation continue de se faire via https://nominatim.openstreetmap.org (cf. https://github.com/YesWiki/yeswiki/blob/8fdd459e061d84190086c36439e51f9c98d81a2a/tools/bazar/presentation/javascripts/geolocationHelper.js#L472-L479) avec une temporisation de 1s entre chaque requête comme l'exige la spécification de cette api
 - **L'implémentation ne marche qu'avec la France**
   - pour l'auto-complétion, effectivement, ça ne marche qu'en France.
   - pour les autres pays, nous pourrions rajouter du code [ici](https://github.com/YesWiki/yeswiki/blob/8fdd459e061d84190086c36439e51f9c98d81a2a/tools/bazar/presentation/javascripts/geolocationHelper.js#L548) pour appeler la bonne route api (personnellement, je trouve que c'est maintenant plus facile de retrouver l'endroit à modifier pour gérer les autres pays)
 
 **Correctifs**:
  - **Autocomplete ne fonctionne pas**
    - pour être sûr d'avoir la même configuration, est-ce que les deux champs "code postal" et "ville" sont bien complétés ? sinon l'auto-complétion du code postal à partir de la ville ne se fait pas. petite capture d'écran : 
![image](https://user-images.githubusercontent.com/67152407/236479373-ee85c345-f7bc-483a-b3af-3d7b38aab5fb.png)
    - j'ai bien conscience que la documentation sur ce point n'est pas très clair. Comme j'ai fait du refactor, je n'ai rien touché à ce point là, en laissant les imperfections
 - **Le geocodage marche super mal**:
   - effectivement, je n'avais pas testé ta configuration et dans ce cas, ce que j'ai introduit produit un résultat moins précis qu'avant. Je vais rajouter un cas à [cet endroit](https://github.com/YesWiki/yeswiki/blob/8fdd459e061d84190086c36439e51f9c98d81a2a/tools/bazar/presentation/javascripts/map-field-leaflet.js#L125-L157) pour dire que si seul le champ `adresse` est fourni sans `ville` ni `code postal`, alors on considère que c'est une recherche de type `q=` et non `street=`
    - >Perso je pense que c'est plus simple de concatener les champs qu'on a pour créer une string en l'envoyer en recherche générale dans nominatim
      - alors effectivement, c'est plus simple mais en pratique, ça fonctionne mal dès que la personne indique le nom d'un lieu (genre `piscine`) dans l'adresse avec un nom de rue qui ne correspond pas à la rue de la piscine. C'est en général les retours que j'ai reçu sur ce point. L'avantage est que maintenant grâce à [ces lignes](https://github.com/YesWiki/yeswiki/blob/8fdd459e061d84190086c36439e51f9c98d81a2a/tools/bazar/presentation/javascripts/map-field-leaflet.js#L125-L157), il est possible de tester plusieurs configurations pour ne garder que la première qui fonctionne. Le souci que tu as vu ne vient pas du fait que j'appelle `town=`, vu que normalement, si je ne me suis pas trompé lors de mon test, ça appelle bien `city=`, mais plutôt que ça appelle `street=` tout seul, ce qui n'est pas une bonne idée (mais je vais corriger)
  - **Message d'erreur**
      - oups, je regarde, ça n'aurait pas dû arriver, je refais mes tests dans cette zone

**Commentaires**
  - **address1 address2**
    - en fait, l'idée est d'avoir une ligne supplémentaire, genre "complément d'adresse" où les personnes vont déposer par exemple, le numéro de l'appartement ou le nom du bâtiment. Ainsi, cette information ne se retrouvera plus dans le champ `bf_adresse` ce qui augmente les chances de trouver le bon point (en général, c'est cet aspect qui fait planter la géolocalisation)
    
 J'espère que déjà mes commentaires répondent à tes questions. Les correctifs arrivent aussi

2023-05-08 17:52 UTC, seballot commented
Salut Jerem ! merci pour la réponse et les commits supplémentaire

**Recherche générale quand uniquement adresse**
Top !

**Autocompletion**
Effectivement ça marche si je renseigne les deux (ville et code postal). Après vu comment elle marche cette autocompletion, on a théoriquement pas besoin d'avoir les deux pour qu'elle s'active, mais bon j'imagine que quasiment tout le monde mets les deux champs donc peut etre pas la peine de faire un fix, sauf si t'as la motiv !

**Adresse1, Adresse2**
Si l'idée est justement de les enlever du geocodage, alors pourquoi les mettre en param du champ map? si les utilisateurices veulent des champs address1&2 tant mieux, ils les créront dans leur formulaire, sans aucune connexion nécessaire avec le champ map, non?

**Config du champ map**
Je proposerai ça :

![image](https://user-images.githubusercontent.com/17404254/236894228-10b7162b-a78b-441f-b8c7-858b09edb005.png)

- ajustement du titre de la section, les champs servent au geocodage non pas à l'autocompletion
- ne pas parler d'autocompletion dans les placeholder. Elle sera automatiquement activée si le champ codepostal et ville est présent, personne sera contre une autocompletion ! et puis ville et codepostal sont avant tout utilisé pour la geolocalisation, donc ça me parait plus cohérent

T'en dis quoi?

2023-05-14 08:37 UTC, J9rem commented
Merci @seballot pour les commentaires

 - **champ adresse1 et adresse2** "Si l'idée est justement de les enlever du geocodage, alors pourquoi les mettre en param du champ map? " justement, je n'avais pas l'intention de les retirer. Pour moi, l'idée est bien de les garder, car ils aident à améliorer la géolocalisation mais en séparant l'adresse dans plusieurs champs, ça permet de donner du sens à l'adresse et de savoir comment la découper (genre adresse = "1, rue Paul Machin", adresse1 = "piscine", c'est plus facile à découper que "1, rue Paul Machin piscine") donc je les conserve mais en mode paramètres avancés

2023-05-14 09:23 UTC, J9rem commented
Normalement @seballot j'ai quelque chose qui s'approche de ce que tu as proposé.

2023-05-15 13:41 UTC, seballot commented
Yop !

Merci pour les changements :)

J'ai poussé un petit fix pour ajuster quelques translations et de mini amélioration sur le UI

Pour moi ça me va en l'état, même si je trouve que l'on complexifie le code avec tous les petits use case pour street1 et street2, et aussi qu'on réinvente un peu la roue avec le geolocationHelper alors que y'a déjà plein de lib qui font ça très bien

Mais go pour merge selon moi, c'est déjà un super avancement, merci !!

2023-05-15 13:59 UTC, J9rem commented
top tes propositions @seballot . Si donc tout est ok pour toi, je te laisse donc valider la PR

2023-05-15 14:37 UTC, seballot approved these changes

2023-05-16 09:09 UTC, mrflos approved these changes
merci  @seballot pour cette review et @J9rem pour la contribution!

2023-05-16 10:19 UTC, J9rem commented
merci pour vos relectures. OK je fusionne

2023-05-16 10:21 UTC, merged