feat(TabsAction): create
YesWiki/yeswiki pull request #1074
Opened 2023-05-21 16:10 UTC by J9rem

fix #908

l'idée est de répondre au besoin de #908 en réutilisant ce qui a été fait pour les onglets dans les fiches.

**pour tester**:
 - utiliser le constructeur de formulaire rubrique 'mise en forme' > 'onglets dans une page' (normalement, le reste des explications est donnée dans `composants`, si ça manque, c'est qu'il faut documenter)

Je vous laisse faire les commits directs pour renommer les menus et options de `composants` (pas besoin de passer par un commentaire ou une revue de PR pour ce point)

2023-05-21 17:25 UTC, mrflos requested changes
Hello @J9rem , merci pour cette proposition, ca me va très bien, sauf pour la partie action {{ChangeTab}} : ca n'a pas de sens pour moi que ce soit une action car on ne peut pas l'utiliser en dehors de cet usage de tab et ca pourrait être ajouté au moment du {{end elem="tab"}}, ou géré par le service, mais de mon point de vue, ca embrouille de l'avoir sous la forme d'une action. Cela t'irait de garder tout le mécanisme mais sans rajouter cette action? Merci d'avance.

2023-05-22 07:04 UTC, acheype commented
merci d'avoir avancé là-dessus @J9rem, et c'est vrai qu'on avait fait un super boulot pour les specs.

j'ai également un soucis avec l'action {{changetab }}, c'était adapté pour les champs mais ça fait bizarre de l'utiliser en tant qu'action. Je serais plus pour suivre les specs et d'avoir des containers à l'instar de {{section}} : l'action {{tab}} et en {{end elem="tab"}} me semble plus approprié.

2023-05-22 08:10 UTC, J9rem commented
@mrflos effectivement, il n'est pas utile de créer une nouvelle action `{{changetab}}`. Je l'ai remplacée par `{{end elem="tab"}}`.

par contre, @acheype , pour éviter de créer une nouvelle action `{{tab}}` je n'ai rien mis (ça aurait été une action vide en plus). Je sais que ça peux perturber les habitudes mais je ne vois pas trop l'intérêt de créer une action vide.

Au passage, j'ai rajouté quelques lignes pour tenter de faire un scroll sur la fenêtre parente (dans le cas du iframe) quand on utilise les boutons de navigation

2023-05-22 12:25 UTC, acheype commented
je trouve ça déroutant pour les utilisateurs d'avoir un `{{end ...}}` sans début d'action associé, ça ne suit pas la logique de YesWiki.
aussi l'intérêt d'un début d'action permet de spécifier des paramètres à chaque onglet. On avait pensé dans les specs à `{{tab default="1"}}` pour que soit sélectionner par défaut un  autre onglet que le premier. On avait aussi pensé à des noms d'ancre pour spécifier quel onglet est ouvert.

et j'avais oublié de le signaler, les boutons pour passer d'un onglet au précédent au suivant sont à mon avis en trop. Cela vient certainement du fait que tu réutilises les dévs des onglets pour les champs. Mais autant je peux comprendre que ces boutons soient utiles dans un formulaire où l'utilisateur doit remplir le formulaire en passant par chaque étape, mais dans un contexte d'onglets classiques ça fait bizarre.

2023-05-22 12:31 UTC, mrflos commented
Hello, 
J'ai un peu de temps là, je vais proposer un commit pour gérer le fait de mettre les boutons de navigation en bas ou pas, et de les numéroter ou pas.

Je suis aussi d'accord pour maintenir l'action {{tab}} pour que la syntaxe soit similaire aux autres composants, et pour en effet ajouter des options comme des classes css, ou éventuellement l'ouverture par défaut (mais faudrait trnacher pour savoir si c'est {{tabs}} qui contiendrait ce paramètre, ou {{tab}}, j'ai l'impression que le parti pris c'est plutot dans tabs, pour faciliter la saisie dans l'interface composants).

2023-05-22 12:35 UTC, acheype commented
cool ! à oui  à la base on avait bien certains arguments faisant partie de tabs et d'autre de tab... c'était à la base plus logique mais je n'avais pas pensé au fait que c'est compliqué ensuite pour l'action builder. donc pourquoi pas tout ramener au niveau de tabs.

2023-05-22 13:17 UTC, J9rem commented
en termes d'implémentation, je trouve que c'est plus facile d'avoir toutes les options dans `{{tabs}}` pour avoir les mêmes paramètres pour chaque onglet (je veux dire, css, classes, position des boutons).
Effectivement, on peut voir pour le paramètre `{{tab selected="1"}}` que je trouve plus parlant que `{{tab default="1"}}` (avis totalement subjectif, donc la première proposition me va aussi).
Je trouve donc que l'action `tab` devient nécessaire sur ce point et donc `{{end elem="tab"}}` ne fera plus rien mais c'est pas grave en fait

2023-05-22 13:24 UTC, mrflos commented
le terme dans bootstrap c'est "active" pour la classe utilisée, mais j'aime pas mal "default" car en effet si l'url pointe vers un autre onglet, celui là devient actif. avec default la nuance reste compréhensible.

sinon pour le {{end elem="tab"}}, il peut continuer à afficher les boutons de nav ou pas, comme ca cela reste le meme mécanisme de partout {{tab}} controle s'il y a bien une balise de fermeture ou affiche une erreur, et ajoute une div avec des classes et options, {{end elem="tab"}} ferme la balise div.

2023-05-22 14:08 UTC, acheype commented
ok ça me va bien ce que vous dites, et super si on peut avoir le rendu par défaut sans le boutons précédents/suivant et que ces derniers avec leur rendus sont en option.

2023-05-22 14:20 UTC, mrflos commented
@J9rem voila ma contrib, j'ai pas compris s'il est possible de rendre une option visible en fonction d'une autre donc là l'option est visible quoi qu'il arrive, c'est peut etre pas le mieux.  
@acheype j'ai pas trop d'avis sur le fait de mettre les boutons en bas par défaut ou pas, j'aime l'avoir quand il y a de contenu, c'est plus ergonomique, mais quand il y a qu'un linge, c'est chargé, je laisse Jérémy trancher.  
Pour les numéros, je pense que c'est mieux de les cacher par défaut, l'utilisateur veut voir son texte sans changements, les numéros sont bien juste pour un truc très procédural, genre formulaire pour les impots.

2023-05-22 14:47 UTC, mrflos commented
ya un bug pour le rendu dans mon code, je fais vite un commit

2023-05-22 14:56 UTC, mrflos commented
c'est corrigé

2023-05-22 15:57 UTC, J9rem commented
@mrflos je fais un refactor , je préfère reprendre la main

2023-05-23 12:44 UTC, acheype commented
Je viens de tester, ça fonctionne super, merci ! Je sens que ça va être la prochaine killer feature de YW, c'était tellement pénible avant de mettre à jour des pages avec onglets  !

Afin d'avoir une action bien terminée, est-ce qu'on ne rajouterait pas une option "Noms personnalisés des ancres (uniques sur la page)" ? Si elle est définie, cela permettrait de remplacer les noms par défaut de type #menuX_Y.
Je verrai d'ailleurs bien cette option dans les "options avancées". Et d'ailleurs, pour ne pas avoir tout au même niveau, j'y rajouterais les champs suivants "Taille des boutons", "Couleur des boutons", "Numéroter les boutons de navigations".

C'est ok pour moi si vous préférez avoir par défaut les boutons de nav en bas. Je me demande juste si ce serait pas visuellement plus sympa d'inclure un petit margin au dessus pour ne pas qu'ils soient collé au contenu de l'onglet. Exemple du rendu actuel : 
![2023-05-23 02-03 - Capture d'écran](https://github.com/YesWiki/yeswiki/assets/8435038/3bcec42f-71a0-413d-8474-d9564449693d)

2023-05-24 09:38 UTC, J9rem commented
Salut @acheype 

>est-ce qu'on ne rajouterait pas une option "Noms personnalisés des ancres (uniques sur la page)" ?

J'ai fait ce [commit](https://github.com/YesWiki/yeswiki/pull/1074/commits/49be0bb9e408f78d11f60aefcebbe3aa03eca4dd) où je propose une génération automatique et unique d'un slug (pour éviter que l'usager ait à retaper un identifiant à chaque fois, genre je propose le mode pas trop d'actions).

> dans les "options avancées" "Taille des boutons", "Couleur des boutons", "Numéroter les boutons de navigations".

done https://github.com/YesWiki/yeswiki/pull/1074/commits/8d688f11ddc03e8b2f2d88aed3295c2d68f7ef31

> inclure un petit margin au dessus pour ne pas qu'ils soient collé au contenu de l'onglet.

J'ai fait une proposition dans ce commit https://github.com/YesWiki/yeswiki/pull/1074/commits/8d6499d74e01c757b31d99813caa8a7531351bfc qui permet de définir une classe css pour l'onglet et qui encapsule les boutons de navigations dans un `div` avec une classe css qui permet de mettre un `margin`.
**Je vous laisse faire un commit direct pour les ajustements du css**

Que penses-tu de tout ceci ? je pense que la PR est quasi mure maintenant

2023-05-24 09:40 UTC, J9rem commented
Au passage, j'ai vérifié, ça fonctionne même si quelqu'un essaie d'imbriquer des onglets (même si en termes d'UX c'est pas beau) et ça fonctionne toujours pour les fiches bazar

2023-05-24 14:51 UTC, acheype commented
Je viens de tester tout ça et pour moi, c'est parfait comme c'est là !

Côté slug, c'est une super idée car plus léger pour l'utilisateur et ça répond parfaitement à à mon besoin d'avoir des noms d'onglets qui ont du sens !

et nickel pour les paramètres avancés et l'encapsulage des boutons de nav et le margin-top par défaut à 10.

Merci !

2023-05-24 14:52 UTC, acheype approved these changes

2023-05-24 19:31 UTC, mrflos approved these changes
Juste une remarque sur le css, pour les composant système c'est bien utiliser des unités en em plutôt qu'en pixel, comme ca cela cela s'adapte bien en fonction de la taille de police utilisée.
Beau travail sinon, merci!

2023-05-24 19:31 UTC, mrflos commented on styles/yeswiki-base.css
> +  margin-top: 10px;
plutot mettre 1em pour garder des marges relatives à la taille de la police utilisée

2023-05-25 07:27 UTC, merged