feat(bazar) : option for geoloc field to show map in entry view
YesWiki/yeswiki pull request #1094
Opened 2023-08-16 18:44 UTC by mrflos

## Description of pull request / Description de la demande d'ajout

Add an option on bazar's `geolocation` field to show a map with the marker of the entry

2023-08-16 21:15 UTC, J9rem commented
@mrflos merci pour la PR, je pourrai regarder et commenter la PR à partir de début septembre. J'espère que ça te va.
En première remarque rapide, je dirais qu'il y a:
 - utilisation de variables `$GLOBALS` qui pourraient être éviter dans `MapField`
 - écriture de `javascript` à partir d'un template `twig`, alors que pour la stabilité, il vaudrait mieux mettre le `javascript` dans un `.js` et uniquement définir via le `twig` une variable `javascript` utilisée par ce script

2023-08-16 23:13 UTC, mrflos commented
Hello @J9rem , merci pour ton rapide retour.   
J'ai pris en compte tes remarques, mais je ne vais pas pouvoir attendre jusqu’à septembre pour ta revue de code, je vais voir si @seballot est dispo, j'ai encore beaucoup de PR en stock plus consistantes (duplications de fiches, import formulaires/fiches améliorés, refacto installateur), et j’espérais finir tout cela assez rapidement.

SI tu relis en septembre il sera encore possible de changer des choses a postériori.

2023-08-17 07:43 UTC, J9rem reviewed
Merci @mrflos pour les correctifs.
Je viens de relire et je vois qu'il y a utilisation de `$wiki->config` qui est modifiable en écriture depuis tout endroit du code.
Lors du refactor 2021, Sebastien a introduit `$params` qui est compilé lors de l'exécution de `YesWiki::loadExtensions` et qui n'est plus modifiable ensuite assurant plus de stabilité dans le code

2023-08-17 07:43 UTC, J9rem commented on tools/bazar/fields/MapField.php
> +        if (!empty($this->showMapInEntryView) && $this->showMapInEntryView==='1' && ( $wiki->getPageTag() === $entry['id_fiche'] || (!empty($wiki->config['showMapInEntryView']) && $wiki->config['show
```suggestion
        $params=$this->getService(\Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface::class);
        if (!empty($this->showMapInEntryView)
          && $this->showMapInEntryView==='1' 
          && ( 
             $wiki->getPageTag() === $entry['id_fiche']
             || (
                $params->has('showMapInEntryView')
                && $params->get('showMapInEntryView') === true
              )
            )) {
```
Je fais 2 propositions:
 1. casser la longue ligne pour en faciliter la relecture
 2. ne pas utiliser `wiki->config` mais `params` qui est plus stable car non modifiable par un autre bout du wiki après compilation dans `LoadExtension`
 
 Pour l'utilisation de `params`, il faudrait aussi ajouter dans `tools/bazar/config.yaml` le paramètre `showMapInEntryView`, pour éviter les erreurs et ajouter la ligne `        'showMapInEntryView'` à `bazar_editable_config_params`(toujours dans le même fichier) pour permettre sa modification depuis `?GererConfig`
 
```yaml
  bazar_editable_config_params:
   -'...'
   - 'showMapInEntryView'
```

2023-08-17 14:12 UTC, J9rem commented
@mrflos j'ai encore beaucoup de PR en stock plus consistantes (duplications de fiches, import formulaires/fiches améliorés, refacto installateur)

Si tu veux que nous puissions bénévolement relire tes propositions avec un temps par trop long quand tu demandes la PR, je pense que tu pourrais dores et déjà publier tes branches de travail pour que nous puissions comprendre ton code et poser des questions tranquillement en amont pour ne pas être dans l'urgence de les valider en 2 ou 3 jours quand tout est fini.

En tout cas, je ne pourrai pas revoir tes PR avant début septembre.

2023-08-17 15:05 UTC, mrflos commented
Oui c'est prévu mais faut quand meme que ca marche un peu avant.
Et Sebastian est missionné sur la revu des PR sur les imports dans bazar donc je le solliciterai lui en premier

2023-08-17 15:15 UTC, mrflos commented on tools/bazar/fields/MapField.php
> +        if (!empty($this->showMapInEntryView) && $this->showMapInEntryView==='1' && ( $wiki->getPageTag() === $entry['id_fiche'] || (!empty($wiki->config['showMapInEntryView']) && $wiki->config['show
en fait le `showMapInEntryView` est justement prévu pour être changé, le principe est que la carte du point dans une fiche n'apparait que si l'on est sur la fiche dans une page entière appelée (ou son iframe), et le   `showMapInEntryView` permet de pouvoir l'afficher dans d'autres contextes : par exemple dans la vue map, cela n'a pas de sens que dans la popup de la carto, il y ai la carto du marqueur de la fiche, mais pour une vue accordéon ou autre template, cela ferait sens. Il serait donc possible dans le template d'initialiser cette valeur, le temps de l'affichage du template, et d'avoir la feature.
Je ne suis pas super satisfait du mécanisme, mais cela est relativement simple a implémenter et ne change pas le comportement par défaut, faudrait juste trouver ailleurs que dans une variable globale, ou dans la configuration en globale.

2023-08-17 15:25 UTC, J9rem commented on tools/bazar/fields/MapField.php
> +        if (!empty($this->showMapInEntryView) && $this->showMapInEntryView==='1' && ( $wiki->getPageTag() === $entry['id_fiche'] || (!empty($wiki->config['showMapInEntryView']) && $wiki->config['show
dans ce cas, il vaut mieux utiliser un service qui stocke cette valeur modifiable et l'interroger pour connaître la valeur. 
Ce sera plus fiable dans le temps et plus facile à debugger.
L'usage de `$GLOBALS` ou de `$wiki->config` en mode ouvert à tout le monde, n'aide vraiment pas à relire le code quand ça bug.

2023-08-17 15:25 UTC, J9rem commented on tools/bazar/fields/MapField.php
> +        if (!empty($this->showMapInEntryView) && $this->showMapInEntryView==='1' && ( $wiki->getPageTag() === $entry['id_fiche'] || (!empty($wiki->config['showMapInEntryView']) && $wiki->config['show
et dans ce cas, pas besoin de définir de variable dans `config.yaml`

2023-08-17 15:27 UTC, J9rem commented
>Et Sebastian est missionné sur la revu des PR sur les imports dans bazar donc je le solliciterai lui en premier

merci donc de ne pas me mettre en relecteur s'il y a déjà des personnes payées pour le faire. (Tu peux toujours mettre un ping dans la description de la PR mais on moins je comprends que tu n'attends pas que j'ai terminé la relecture pour fusionner)

2023-08-17 15:28 UTC, mrflos commented on tools/bazar/fields/MapField.php
> +        if (!empty($this->showMapInEntryView) && $this->showMapInEntryView==='1' && ( $wiki->getPageTag() === $entry['id_fiche'] || (!empty($wiki->config['showMapInEntryView']) && $wiki->config['show
c'est un peu "overkill", je vais plutot voir pour en faire un param de bazarliste

2023-08-17 15:30 UTC, J9rem commented on tools/bazar/fields/MapField.php
> +        if (!empty($this->showMapInEntryView) && $this->showMapInEntryView==='1' && ( $wiki->getPageTag() === $entry['id_fiche'] || (!empty($wiki->config['showMapInEntryView']) && $wiki->config['show
c'est un autre moyen auquel je n'avais pas pensé `paramètre de bazarliste` mais effectivement, c'est aussi un moyen fiable (qui demande un peu de réglage pour le voir dans les options après)

2023-08-17 15:32 UTC, mrflos commented
oui, c’était mon intention sur cette petite PR, de vous mettre en relecteurs juste pour que vous le voyez passer.  
J'éviterai de te solliciter dans le futur sur les PR, pas de soucis!

2023-08-21 16:48 UTC, seballot requested changes
Wesh !

Cool la feature ! 
J'ai juste des problèmes d'affichage dans le mode liste accordéon. J'ai vu que tu as mis un resize mais ça n'est pas suffisant chez moi

![image](https://github.com/YesWiki/yeswiki/assets/17404254/cdde418d-2e3b-407c-b126-4d267aa3062d)

2023-08-21 16:48 UTC, seballot commented on tools/bazar/fields/MapField.php
> +            && ($currentUrlIsEntry || $showMapInListView)
Yop !

Pour moi en terme utilisateur ça ferait plus de sens

```
if ($this->showMapInEntryView === '1' && $currentUrlIsEntry || $showMapInListView)
```

2023-08-21 16:48 UTC, seballot commented on docs/actions/lang/actionsbuilder_fr.inc.php
> +    "AB_bazar_commons2_showmapinlistview_hint" => "Si des coordonnées sont présentes dans la fiche et l'option est activée dans le champ géolocalisation",
cf mon autre commentaire

`"AB_bazar_commons2_showmapinlistview_hint" => "Uniquement pour les fiches qui ont été géolocalisées"`

2023-08-22 10:25 UTC, mrflos commented on tools/bazar/fields/MapField.php
> +            && ($currentUrlIsEntry || $showMapInListView)
oui, je me posais la question, c'est confus d'avoir 2 endroits a vérifier pour afficher le point

2023-08-22 10:28 UTC, mrflos commented
> Cool la feature ! J'ai juste des problèmes d'affichage dans le mode liste accordéon. J'ai vu que tu as mis un resize mais ça n'est pas suffisant chez moi

Oui c'est encore buggué, je vais tenter de faire du lazyloading de la carte, peut etre avec https://developer.mozilla.org/fr/docs/Web/API/Intersection_Observer_API

2023-08-23 19:47 UTC, mrflos commented
Voila @seballot j'ai : 
- changé le comportement du champ comme tu le proposais
- trouvé un moyen de faire du lazyload des cartes pour que cela marche dans des accordéons et autres (en vanilla js en plus)
- recyclé une variable `$actionObjects;` qui traînait dans la classe wiki pour garder une trace des actions appelées, j'en avais besoin pour retrouver le contexte du bazarliste et ses paramètres a partir du Mapfield

Mes test ce sont avérés concluants mais a vérifier!

2023-08-24 16:41 UTC, seballot commented
Yop !

Désolé mais chez moi le trick du actionObjects ne marche pas, la variable `$wiki->actionObjects` est un tableau vide... du coup la map preview n'est jamais affichées dans le bazarlist

Idées alternatives

1. enlever le param showMapInListView du bazarliste et se fier uniquement au paramétrage du formulaire. On peut avec du css masquer le map-field dans les templates pour lesquels ça n'a pas de sens (a priori juste les tmeplate map non?)

2. ou bien, passer le paramètre showMapInListView lors de l'appel api qui permet de rendre la fiche depuis le bazarliste `http://localhost:81/?api/entries/html/LovelaceAda&fields=html_output`

Perso j'irai plutot sur 1.

D'autres idées?

2023-08-24 17:29 UTC, mrflos commented
Je viens de basculer https://testing.yeswiki.net/doc/?PagePrincipale sur la branche feat/map-for-entry-view et cela marche avec les 3 bazarlistes appelés..

T'as pas une histoire de cache docker ou de classes yeswiki non mise a jour?

2023-08-24 17:45 UTC, seballot commented
ah en fait c'est avec le bazar dynamique que ça marche pas, cf https://testing.yeswiki.net/doc/?PagePrincipale

2023-08-24 18:25 UTC, mrflos commented
ah ok merci, je vais pouvoir regarder !

2023-08-29 10:43 UTC, mrflos commented
@seballot j'ai fait ce que j'ai pu pour permettre l'usage de listes dynamiques.  
J'ai pris l'option 2 avec param GET pour passer l'option `showMapInListView`, ca donne plus de controle, et le code html contient ce qu'il faut, les ccs pour cacher, je pense que ca pose des soucis d'accessibilité, et de performances
Mes connaissances en vuejs étant limitées, j'ai fait ce que j'ai pu car c'est a mon avis difficile de checker ce qu'il se passe a l'injection de html des fiches, car cette action est appelée dans un deuxième temps et un peu en dehors du composant bazarlist.  
Ya sans doute mieux a faire, mais j'ai ni le temps ni la compréhension de vuejs pour faire mieux que cela, mais je considere que la PR est opérationnelle.

2023-08-29 13:02 UTC, seballot commented
Wesh !

eh bien, ça rajoute pas mal de complexité cette histoire de MapField, qui l'eu cru !

Si tu as le temps (et la motive) je pense que ça serait bien d'au moins extraire le code que tu as rajouté dans baza-list-dynamic dans un fichier séparé. Le fichier bazar list est déjà bien costaud, et là rajouter de la logique très spécifique ça nuit à la lecture je pense. Le top serait d'ailleurs dans profiter pour DRY car la les bout de code javascript sont quasi identique entre dynamic et non dynamic

Mais si pas le temps, pas de soucis pour merger comme ça ! 

zoubs

2023-08-29 13:37 UTC, mrflos commented
Yes je veux bien, j'ai tenté de DRY, mais mon soucis c'est que je ne maîtrise pas assez les concepts vuejs pour être capable d'appeler mes fonctions depuis des méthodes vue, par exemple, j'ai pas compris comment on sait quand le dom contient les changements (on dirait que vue n'est pas dans le vrai dom de la page mais dans une abstraction propre a vue).  
Leaflet a besoin d'un id du vrai dom pour instancier la carte et j'ai pas reussi a bien faire le lien avec l'appel ajax de la fiche bazar.
Si tu as le temps d'un coup de fil pour m'expliquer comment procéder, je veux bien, apres je fini

2023-08-29 14:12 UTC, seballot commented
yes je suis dispo maintenant sur framateam si tu veux

------- Original Message -------
On Tuesday, August 29th, 2023 at 15:38, Florian ***@***.***> wrote:

> Yes je veux bien, j'ai tenté de DRY, mais mon soucis c'est que je ne maîtrise pas assez les concepts vuejs pour être capable d'appeler mes fonctions depuis des méthodes vue, par exemple, j'ai pas compris comment on sait quand le dom contient les changements (on dirait que vue n'est pas dans le vrai dom de la page mais dans une abstraction propre a vue).
> Leaflet a besoin d'un id du vrai dom pour instancier la carte et j'ai pas reussi a bien faire le lien avec l'appel ajax de la fiche bazar.
> Si tu as le temps d'un coup de fil pour m'expliquer comment procéder, je veux bien, apres je fini
>
> —
> Reply to this email directly, [view it on GitHub](https://github.com/YesWiki/yeswiki/pull/1094#issuecomment-1697464540), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AEEZCXR7N4PDRGJVDOES23DXXXWD5ANCNFSM6AAAAAA3S6JX7E).
> You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-08-29 15:43 UTC, mrflos commented
ya un truc chelou avec les force push, ca recupere la paternité des commit d'avant...  
Apres OSEF mais bon, je ne pourrais pas marquer sur mon CV que j'ai contribué a mettre des cartes dans les fiches wiki!

2023-08-29 15:46 UTC, merged