Fix Docker
YesWiki/yeswiki pull request #1127
Opened 2023-12-21 15:45 UTC by seballot

Yo !

@oiseauroch merci pour les commits sur docker! néanmoins j'ai eu des soucis sur ma machine :) Voilà mes retours

1. Déjà, je pense que ça aurait été bien de faire **un message à tous les devs** pour les informer qu'ils vont devoir rebuilder, et leur fournir des explications sur la marche à suivre : supprimer leur `wakka.config.php` ou qu'ils le modifient avec les nouvelles bonnes valeurs, supprimer son ancienne image (car elle a le même nom), et s'assurer que tout fonctionne bien. Perso, ça fait 1h30 que je bataille pour re avoir un environement de dev, ça fait pas super plaisir :) surtout quand ça marchait avant héhé
2. **J'ai ajusté la doc**, qui n'était plus bonne, notamment sur les valeurs à renseigner lors de l'install, et sur les commandes à lancer
3. **Chez moi le `docker-compose-dev.yml` ne fonctionne pas correctement**, quand je up j'ai cette erreur `yeswiki-web  | nginx: [emerg] host not found in upstream "yeswiki-app:9000" in /etc/nginx/nginx.conf:34`. 
4. **Je ne comprends pas vraiment ce qu'apporte le docker-compose-dev.yml,** est ce que tu voudrais bien m'expliquer? je suis pas un expert docker. Est ce que le docker-compose de base ne devrait pas etre celui de dev, et plutot en créer un pour la prod? car je pense qu'aujourd'hui docker est quasi uniquement utilisé en dev pour yeswiki
5. Lorsque j'ouvre un **terminal sur mon container** avec `docker exec -it yeswiki bash`, il n'y a ni composer ni yarn, du coup je ne peut pas gérer mes dépendances (il faudrait que j'installe yarn et composer sur ma machine locale, avec la bonne version etc...). Je pense que c'est du aux changement qu'il y a eu sur le dockerfile. Est ce qu'il y a un moyen d'avoir accès à ces commandes? car sinon IMHO cela defeat le but de docker, non? 

En tout cas super content qu'il y ait de nouveau dev sur yeswiki, meme si j'avoue cette expérience docker m'a un peu frustré sur le coup hi hi

Bise !

2023-12-21 16:12 UTC, ppom0 commented
Hello !
Déso pour le breaking change, olala :/
De ce que j'avais compris, l'image docker précédente était pas fonctionnelle ou pas utilisée, c'est pour ça qu'on s'était permis·es de tout modifier comme ça. Désolé·e du coup :bow: 
Je crois que le docker-compose-dev.yml est pas fini. Qu'il devrait aller avec un nouveau `Dockerfile.dev`

En fait le Dockerfile qu'on a fait est bien pour de la prod : image la plus légère possible, sans yarn et composer. Mais pour du dev, c'est pas du tout adapté du coup.

Je ne me souviens pas à quoi ressemblait l'ancien Dockerfile, mais il était ptet mieux adapté à du dev. Ptet qu'un rollback s'impose, pour le dev.
Et c'était un chantier qu'on n'avait pas fini, donc c'est une erreur que ce soit sur la branche principale comme ça, nostra culpa :/

2023-12-21 16:15 UTC, ppom0 commented
Du coup, merci pour ta PR, c'est déjà ça de boulette en moins.

Pour la suite, je sais pas quoi proposer (pis je viens d'arriver sur YesWiki moi !)

On pourrait par exemple reprendre l'ancien setup docker pour le dev, et faire de notre contrib un truc "spécial prod", qui aurait plus vocation à finir sur le docker hub par exemple.

2023-12-21 16:16 UTC, ppom0 commented
Est-ce qu'il y avait des points de friction avec l'ancien Dockerfile ? Des choses à améliorer pour l'UX de dev ?

2023-12-21 17:04 UTC, mrflos commented
Hello!
Pour remettre un peu de contexte sur cette histoire de docker: voici l'ancien compose https://raw.githubusercontent.com/YesWiki/yeswiki/6bb36ac7013ba87005af02e04c0f3b5d32cc01cd/docker-compose.yml
Il ne marchait pas pour les étudiant.es qui avait des configurations variées entre les macbookpro arm M2, les PC windows etc, et il y avait l'opportunité de faire une image plus légère en faisant en sorte de ne pas garder les outils de builds (il y avait aussi l’idée de passer de debian a alpine, plus légères encore).  
Dans l'ancienne image docker, on utilisait une image fourre tout avec une assez vieille version de php et composer, du node dedans, etc,.. mais en effet elle contenait tous les outils de dev comme un mail catcher et phpmyadmin.

Désolé c'est moi qui ait rapidement fusionné la branche, car j'avais la semaine avec les étudiant.es dockerophiles qui démarrait, on aurait du aller plus loin dans la concertation avant de mettre ca dedans, sorry... (\<tacle gratos>mais je remarque que la fameuse promesse de docker d’écrire 4 lignes dans un fichier et que cela marche de partout ne semble pas tenue\</tacle gratos>).

En tout cas, la solution me semble toute trouvée puisqu'il suffirait donc de faire un docker compose de dev (et la remarque de @seballot d'avoir le docker-compose par défaut en mode dev, et d'avoir celui de production sous un nom du genre docker-compose-prod.yaml ), en essayant d'avoir un truc cohérent entre les deux (meme images sources? même secrets?) et donc de remettre la stack de dev en mode je fais docker-compose et ca juste marche, et c'est parti!

Je suis pas fort en docker, mais je peux faire gros beta testeur, et documenter le tout. Quelqu'un.e de dispo pour regarder cela a l'occasion?

2023-12-21 18:44 UTC, seballot commented
salut @ppom0, merci pour tes retours !

Ok je comprend mieux l'idée de faire un truc très léger pour la prod. Mais effectivement c'est pas adapté au dev :)

D'ailleurs je viens de comprendre l'histoire des volumes avec le docker-compose-dev, car en fait sur le docker-compose.yml si je fait des changement sur mon éditeur sans etre connecté sur le container, les changements ne sont pas pris en compte. Mais meme en virant le volume, peut etre à cause de la conf nginx, si je change un fichier javascript rien n'est pris en compte dans mon navigateur. donc vraiment je peux pas dev lol

Si @ppom0 ou @oiseauroch vous êtes motivé à refaire une config plus adaptée au dev, ça serait avec plaisir. Si vous avez pas le temps, je le ferai, dites moi

a+

2023-12-21 20:06 UTC, seballot commented
Ps: @mrflos je suis très déçu de voir qui tu priorise entre des étudiants inconnus avec leur macbook dernier modèle, et ton pote linuxien grand contributeur de yeswiki :P

2023-12-22 06:14 UTC, mrflos commented
@seballot je ne priorise pas, t'inquietes, juste je ne maitrise pas encore assez cette techno pour faire les bons choix, désolé!  
La prochaine fois que je te voies IRL, on te fera un setup nix aux petits oignons et tu pourras enfin t'echaper de ta prison dorée dockerisée :yum:

2023-12-22 09:04 UTC, oiseauroch commented
> Si @ppom0 ou @oiseauroch vous êtes motivé à refaire une config plus adaptée au dev, ça serait avec plaisir. Si vous avez pas le temps, je le ferai, dites moi

Hello, je vois pour faire ça pendant les vacances. Effectivement, l'image crée est plus pour la prod que pour le dev

2024-01-04 13:56 UTC, oiseauroch commented
Normalement, l'image fonctionne si vous voulez tester.

2024-01-04 22:52 UTC, seballot reviewed
Yo !
Super merci pour ce travail !
J'ai pu builder et lancer les containers sans encombres, la doc est top !

En revanche quelques trucs ne fonctionnent pas, cf mes commentaires

A+
Sebastian

2024-01-04 22:52 UTC, seballot commented on docker/docker-compose-prod.yml
je crois que ce fichier devrait appeler le docker-prod non?

2024-01-04 22:52 UTC, seballot commented on docker/docker-compose.yml
> +    yeswiki-web:
Juste par curiosité, quel est l'intérêt d'avoir deux container yeswiki-app et yeswiki-web, et pas un seul?

2024-01-04 22:52 UTC, seballot commented on docker/docker-compose.yml
> +    mail:
Top ça !!

2024-01-04 22:52 UTC, seballot commented on docker/dockerfile_test.yml
ce fichier n'est pas utilisé, et l'extension ne correspond pas, un oubli peut etre?

2024-01-04 22:52 UTC, seballot commented on docker/entrypoint.sh
Perso j'aime pas trop lancer les commandes type composer et yarn dans les entrypoint, car si elles foirent, alors le container ne démarre pas. Et comme il démarre pas tu peux pas t'y connecter pour fixer d'éventuel truc pour que ça passe, faut donc utiliser un entrypoint special pour débugger etc..

Ca me dérange pas de laisser comme ça, juste je partage un retour d'expérience

2024-01-04 22:52 UTC, seballot commented on docker/README.md
> +docker compose exec yeswiki-app yarn install
Chez moi ces commandes ne fonctionnent pas

`OCI runtime exec failed: exec failed: unable to start container process: exec: "yarn install": executable file not found in $PATH: unknown`

Aussi, si je me connecte au container avec un `docker compose exec yeswiki-web bash` et que ensuite je fait un yarn ou un composer, la commande se lance mais échoue à cause de problèmes de permissions

`yarn install` => `error Error: EACCES: permission denied, unlink '/var/www/html/node_modules/@babel/parser/CHANGELOG.md'`

`composer install` => `In Filesystem.php line 288:=Could not delete /var/www/html/vendor/bin/carbon:  `
                                                    
alors que dpeuis le entrypoint ça fonctionne. (Ps: j'ai bien créé un docker/.env avec mon user id & gorup)

2024-01-07 09:26 UTC, ppom0 commented on docker/docker-compose.yml
> +    yeswiki-web:
Je ramène ma fraise, je peux pas justifier tout ce qui a été fait ici mais pour une question générale je peux ^^
Ça fait partie de la "philosophie" de Docker, avec généralement un seul processus qui tourne par conteneur. Ça a plusieurs avantages,
- le meilleur étant de pas avoir à maintenir l'install de nginx : on utilise l'image dédiée, avec une conf adaptée aux conteneurs et tout. Alors que si on se fait un `apt install nginx` dans la même image, on n'a pas ces garanties
- le second étant de tirer parti de l'ordonnanceur de Docker : si le PID 1 du conteneur s'éteint, le conteneur fail. Si tu veux faire un conteneur correct avec plusieurs processus, il va falloir que tu lances un mini ordonnanceur toi-même, ou le 2e processus sera pas du tout "géré"

Voilà pour l'*info drop*! Je suis sûr·e que y'a d'autres explications plus charismatiques sur le web :')

2024-01-07 12:58 UTC, mrflos requested changes

2024-01-07 12:58 UTC, mrflos commented on docker/dockerfile
> +RUN groupadd -g "${UID}" yeswiki \
ya une typo, je croies : `${UID}` devrait être `${GID}`

2024-03-15 08:46 UTC, mrflos commented
ping @ppom0 @oiseauroch ca vous dirai une session pair programing avec moi comme beta testeur neophyte de docker, histoire de documenter et valider que nos 2 scenarii docker prod et dev fonctionnent puis le merger?

2024-03-17 13:45 UTC, ppom0 commented
Ça me dit, en journée jeudi ou vendredi ! @mrflos @oiseauroch

2024-03-17 19:31 UTC, oiseauroch commented
Dispo aussi jeudi ou vendredi !

2024-03-19 09:28 UTC, mrflos commented
@ppom0 @oiseauroch ça irait jeudi matin ? Genre 11h?

2024-03-19 12:11 UTC, ppom0 commented
ok pour moi !

2024-03-21 19:30 UTC, mrflos approved these changes

2024-03-22 13:34 UTC, merged