refactor(FILTER_SANITIZE_STRING): use FILTER_SANITIZE_STRING_BKUP
YesWiki/yeswiki pull request #1163
Opened 2024-05-17 06:54 UTC by J9rem

**Contexte**:
 - je me rends compte qu'avec `php 8.3` et peut-être d'autres versions plus anciennes, l'utilisation de la constante : `FILTER_SANITIZE_STRING` crée un warning intempestif.

**Propositionn**:
 - définition d'une nouvelle constante `FILTER_SANITIZE_STRING_BKUP` de même valeur

2024-05-17 07:02 UTC, mrflos commented
Hello je ne suis pas chaud pour supporter une constante que personne d'autre dans le monde utilise... 
Si j'en croies la doc :
![image](https://github.com/YesWiki/yeswiki/assets/124845/ff692a70-fba7-4874-8309-60b457a71256)
C'est plutot `htmlspecialchars` qui ferai office de remplacement

2024-05-17 10:35 UTC, mrflos requested changes
Plutot passer par htmlspecialchars que de  passer par la methode qui appelle cette constante, ou changer le comportement de filterInput pour lui dire quoi faire avec les strings.
Related https://stackoverflow.com/questions/69207368/constant-filter-sanitize-string-is-deprecated

2024-05-22 18:22 UTC, J9rem commented
@mrflos je pense que je me suis mal expliqué.

Effectivement, il faut utiliser quelque chose comme https://stackoverflow.com/questions/69207368/constant-filter-sanitize-string-is-deprecated et c'est l'objectif de la nouvelle méthode de `SecurityController` (qui permet de factoriser le code).

Ma première proposition porte effectivement à confusion avec la constante dépréciée. Je viens de faire une nouvelle proposition qui ajoute un argument à la méthode `SecurityController::input` pour déclencher l'émulation de `FILTER_SANITIZE_STRING` sans utiliser la valeur de cette constante dépréciée.

2024-05-23 09:07 UTC, J9rem commented
J'ai testé ceci:
 - copier de https://repository.yeswiki.net/doryphore/yeswiki-doryphore-4.4.4.zip
 - installation du wiki (rewrite_mode off, pas de robot)
 -  paramètres:
   - `'archive' => ['preupdate_backup_activated' => false]`
   - `'debug' => 'yes'`
 - mise à jour du thème `margot`
 - mise à jour (réinstallation) de YesWiki `doryphore 4.4.4`
 - modification de la page `GererMisesAJour` => `{{update version="doryphore-dev"}}`
 - je clique sur `Changer de version`
 - => **la mise à jour ne se termine pas** et des messages d'erreurs apparaissent
 - avec les correctifs apportés par cette PR, tout fonctionne et il n'y a plus d'avertissement

2024-05-26 10:06 UTC, mrflos approved these changes
Bon j'approuve a contre cœur cette PR faute de temps, mais il y a plusieurs problèmes:
- le fix sur la migration, fort utile, n'a rien a voir avec cette PR et aurait du faire l'objet d'une autre PR
- rajouter des attributs booleen et faire des opérateurs ternaires en profusion rendent le code pas très lisible
- revoir tous les appels de la méthode, c'est difficile a relire et il peut facilement y avoir des oublis
- il aurait été plus judicieux de filtrer avec le composant Request de Symfony, plutôt que de passer par des méthodes maison (mais j'ai conscience que c'est plus de temps de travail)

2024-05-26 10:06 UTC, merged