Actions builder
YesWiki/yeswiki pull request #498
Opened 2020-09-28 16:38 UTC by seballot

Un utilisateur graphique pour construire des actions dans l'éditeur

La système de documentation est générique, sauf si il y a des champs trop spécifique il devrait être possible de documenter l'ensemble des actions de yeswiki sans autre ligne de code (enfin sauf si on considère les fichier YAML comme du code, lol !)

il y a un README dans `docs/actions`

2020-10-12 15:40 UTC, mrflos commented
Bonjour, merci de me faire signe quand il faut merger dans doryphore pour de vrai!  
Vu de loin, je voies 2 choses potentiellement chiantes voire bloquantes : 
- l’internationalisation : peut etre prévoir un suffixe par langue genre `bazarliste.fr.yml` et `bazarliste.en.yml` avec un mécanisme pour prendre une version par défaut (la fr ? ) si l'action n'est pas disponible dans la langue choisie. Autre option, ne faire que la version fr comme actuellement et trouver un mécanisme d’internationalisation genre https://github.com/kazupon/vue-i18n
- comment gérer les actions avec un gris gris début et un gris gris fin (genre `{{grid}}` et `{{end elem="grid"}})` ? Peut être un paramètre en yaml genre `closingAction : {{end elem="grid"}}` qui se rajoute a la fin? Bref, potentiellement un beau bazar a venir ;)

2020-10-12 18:31 UTC, seballot commented
Yop ! j'ai des petits trucs à régler avant de merger aussi
- [x] Vérifier que toute la docu des actions bazar est correcte
- [x] Je crois que certains paramètres de certaines actions ne fonctionnent pas (genre afficher initialement en position déroulé pour les facettes), en profiter pour les fixer ! 
- [x] quand on clique dans l'éditeur sur une action, afficher le bouton "edit" uniquement si l'action est documentée par l'action builder
- [x] quand on clique dans l'éditeur une action documentée,  remplacer les options du dropdown "Composants" pour mettre à la place un seul choix "Editer le composant sélectionné"
- [x] prendre en compte l'internationalisation (ou trouver vite fait une combine en attendant)
- [x] gérer le param correspondence pour les actions bazar

Pour les actions qui s'ouvrent et se ferme, on verra ça dans la v2 non? l'idée n'est pas forcément de documenter direct toutes les actions. si déjà on a le bazar opérationnel c'est cool je pense !

2020-10-13 05:47 UTC, mrflos commented
Yes en effet ta todolist est déja bien étoffée en l'état, et c'est déja un sacré pas en avant, donc no soucis pour attendre une v2 pour les actions les plus complexes.  
Pour la position déroulée des facettes, c'est peut etre une incompréhension de ce que c'est sensé faire : il est sensé ouvrir juste la première facette, et laisser les autres fermées, alors que l'autre option laisse toutes les facettes ouvertes.  
Cela marchait avant, même si le comportement peut dérouter..

2020-10-19 16:21 UTC, seballot commented
Yop, j'ai avancé, manque plus que l'internationalisation, et puis un chantier pour éventuellement rapatrier des templates depuis https://github.com/YesWiki/templates-bazar/tree/master/templates ?

2020-10-20 09:11 UTC, mrflos requested changes
mini fautes d'ortograf mais toujours aussi géniale cette avancée, c'est une révolution!

2020-10-20 09:11 UTC, mrflos commented on docs/actions/bazar.yaml
> -    hint: Un champ de type bf_image, bf_baseline sont nécessaire
`Des champs de type bf_image, bf_baseline sont nécessaires`

2020-10-20 09:11 UTC, mrflos commented on docs/actions/bazar.yaml
> -    hint: Un champ de type bf_image, bf_date_debut_evenement sont nécessaire.
`Des champs de type bf_image, bf_date_debut_evenement, bf_date_fin_evenement sont nécessaires.`

2020-10-25 15:44 UTC, seballot commented
C'est bon pour l'internationalisation !

```yaml
label: _t(AB_bazar_label)
previewHeight: 450px
actions:
  commons:
    properties:
      search:
        label: _t(AB_bazar_commons_search_label)
```

```php
<?php
// docs/actions/lang/actionsbuilder_fr.inc.php
$GLOBALS['translations'] = array_merge($GLOBALS['translations'], array(
    // BAZAR
    'AB_bazar_label' => "Afficher les données d'un formulaire",
    'AB_bazar_commons_search_label' => 'Barre de recherche',
));
?>
```

Restera plus qu'à prendre toute la doc et mettre des clés de traductions à la place, faudra faire appel aux bonnes volonté, moi je passe mon tour ah ah :D

2020-10-25 16:59 UTC, seballot commented
Et allez petit dernier du week end, on peut maintenant gérer les actions qui doivent se fermer (comme {{section}})

Je pense que cette PR est prête pour être testée. Y'a plus qu'à maintenant compléter la doc petit à petit

2020-10-26 11:41 UTC, mrflos commented
bravo, super cool, j'ai pas encore eu le temps de regarder, mais cela s'annonce épique, un grand merci!

Juste j'observe que les fichiers de langue sont dans /docs plutot que /lang , il y a une raison?

2020-10-26 12:36 UTC, seballot commented
je les ai mis dans docs/langs, histoire de les distinguer des autres fichiers de langues, mais ça peut biensur facilement se changer si tu préfères !
tu voudrais sinon que je mette tout le code de l'action builder dans tools/actionsbuilder ?

2020-10-26 12:43 UTC, seballot commented
actuellement le code est dans le tools aceditor, mais la doc des actions est dans docs/actions

On peut mettre les fichiers yaml de paramètre dans chaque tool, mais ça me semblait plus simple pour un non dev (genre Laurent) d'accéder à tous les fichiers dans le dossier docs/actions

2020-10-30 10:19 UTC, mrflos approved these changes

2020-10-30 10:27 UTC, mrflos approved these changes

2020-11-01 11:15 UTC, seballot commented
@gatienbataille @sylvainboyer @mrflos  je pense que l'action builder est prêt pour être mergé ! Feu vert?

2020-11-01 17:45 UTC, gatienbataille commented
ok pour moi même si je crois pas que tous les tests aient été effectués mais @furax37 semble avoir déjà fait bcq.

2020-11-02 19:13 UTC, sylvainboyer commented
Une mega avancée. Super méga trop cool.

2020-11-06 08:23 UTC, merged