Custom code
YesWiki/yeswiki pull request #512
Opened 2020-10-19 09:32 UTC by seballot

Yop ! Alors j'ai créé mon premier yeswiki, et j'ai du ajouter du custom code et... j'ai un peu galéré !! ah ah

Je pense que j'ai pas toutes les infos de l'historique et aussi de certains fonctionalités, j'aimerais donc bien en discuter avec vous. J'ai commencé certains commits, mais mieux vaut en discuter d'abords

## Custom Tools
Je n'arrive pas à utiliser le dossier `custom/tools`
J'ai tenté de modifié une action d'une extension déjà existante en créant le fichier `custom/tools/bazar/actions/bazarliste.php` mais ça ne fonctionne pas
J'ai essayé de créé une nouvelle extension avec un action simple `custom/tools/test/actions/testaction.php` mais ça ne fonctionne pas
Est ce que j'ai mal compris à quoi sert ce dossier? 

## Custom templates

#### Dossier templates à la racine du wiki
D'après ce que j'ai compris via le README, c'est un projet similaire aux themes et aux extension mais qui a été abandonné non? je n'ai trouvé qu'un depot templates sur yeswiki (https://github.com/YesWiki/yeswiki-templates-moustic2017)

#### Bazar templates : afficher un fiche
Pour l'instant on peut personnaliser les templates bazar en mettant un dossier type `fiche-ID.tpl.html` dans
`custom/templates/bazar/templates/` ou
`custom/themes/tools/bazar/templates/`
1) je trouve le premier chemin un peu verbeux, j'ai fait en sorte que cela fonctionne aussi avec `custom/templates/bazar`, cela vous convient?
2) je ne comprends pas l'idée de ce deuxième dossier, pour moi les thème sont juste des fichier css. L'idée est elle de modifier un poil certains templates pour changer leur affichage? je ne suis pas sûr que changer le html soit nécessaire, juste avec du css on peut changer déjà beaucoup de choses non?

#### Bazar templates : afficher les résultats
J'ai fait en sorte qu'on puisse ajouter des templates pour bazarliste dans `custom/templates/bazar/templates/` ou `custom/templates/bazar/`, cela vous va?

#### Templates autre que bazar
J'ai essayé de personnaliser le template `modal.tpl.html` du tool `login`, sans succès. j'ai essayé les chemins suivants
`custom/templates/login/templates/modal.tpl.html`
`custom/tools/login/templates/modal.tpl.html`
`custom/tools/login/presentation/templates/modal.tpl.html`

## Manager les fichiers customs
En tant que dev, j'aimerai bien avoir tous mes fichiers custom sur un dépot, comme ça j'ai juste à cloner mon repo dans `custom`. Sauf que actuellement `custom` contient déjà des fichiers README donc ce n'est pas possible (il y aurait un conflit). Est ce que ça vous irai si je change la structure pour le dossier custom soit vide et entièrement git ignoré, et qu'à la place on bouge la doc dans dans docs/custom/README.md ?

Merci pour la lecture et pour votre aide !!
Zoubis

2020-10-20 08:44 UTC, mrflos commented
Merci @seballot pour te lancer dans un nouveau gros chantier !
Par contre, idéalement lancer la discussion avant d'implémenter les features ca peut être un plus ;), aussi écris au moins une fois dans les messages productowner ou tagues @gatienbataille et @sylvainboyer pour qu'ils puissent suivre (vu que c'est chaud déjà pour moi de suivre les devs en ce moment, j'imagine pas pour eux!)

Pour te répondre vite fait : 
1. Custom tools : tu ne peux pas prendre juste un fichier isolé du tools, tu es obligé de prendre l'ensemble du dossier du tools avec le desc.xml pour qu'il soit reconu, sinon cela ne marche pas. Je me demande s'il ne serait pas mieux d'avoir un dossier `custom/actions` et un dossier `custom/handlers/page` pour mettre des actions spécifiques? en théorie il serait possible de le rendre prioritaire sur les autres dossiers et donc `custom/actions/bazarliste.php` pourrait prendre le dessus sur le bazarliste actuel
2. le dossier templates : si tu parles de celui à la racine, il n'est pas abondonné et utilisé par certains plugins comme lms, pour télécharger des templates sans acces ftp. L'
idée était d'avoir les mêmes dossiers a la racine (templates, themes, tools ) que dans custom (custom/templates, custom/themes, custom/tools ) .

Pour simplifier le chemin (et éviter templates/bazar/templates), je ne suis pas contre, l'idée était d'avoir la même structure que dans les tools/monext/presentation mais je suis d'accord que c'est plus lisible

Pour l'utilité du deuxieme dossier, c'est plus pour la retro compatibilité, mais vu aussi qu'on code parfois dans les templates html (bouhh, pas bien), pour par exemple n'afficher que les dates a venir, cela reste plus utile que le css seulement.

Pour les templates des autres tools, c'est peut etre un bug, car en theorie `custom/templates/login/templates/modal.tpl.html` et `templates/login/templates/modal.tpl.html` devraient marcher.. Je pourrais regarder si tu veux

Pour le dossier custom, c'est en effet une bonne idée, mais faut pas un .gitkeep ou au moins un fichier pour que le dossier soit dispo au téléchargement? je suis pour qu'il soit vide et facilement déployé avec un dépot git, mais je voudrais qu'il soit quand meme crée et présent dans le zip

2020-10-20 08:50 UTC, mrflos requested changes
manque juste un chemin à priori

2020-10-20 08:50 UTC, mrflos commented on tools/bazar/libs/bazar.fonct.php
>          'templates/bazar/templates/fiche-'.$fiche['id_typeannonce'].'.tpl.html',
il manquerait `'templates/bazar/fiche-'.$fiche['id_typeannonce'].'.tpl.html',`

2020-10-20 09:44 UTC, seballot commented
Yop ! merci pour tes réponses :)

> Custom tools
Ok pour copier la totalité du tools ! c'est souvent utilisé?

> Je me demande s'il ne serait pas mieux d'avoir un dossier custom/actions et un dossier custom/handlers/page pour mettre des actions spécifiques? 
Je suis d'accord :) Eventuellement aussi un custom.css et un custom.js? sinon il faut modifier le squelette pour include ses propres fichiers css et javascript

> dossier template à la racine
mmm, perso je trouve que ça embrouille, parce que des templates y'en a dans les tools/XXX/presentation/templates, dans les themes, dans le dossier racine templates, et dans custom/templates !! pourquoi le LMS met pas juste les templates dans le tools LMS? ou alors si ce dossier racine template est géré de manière automatique juste par certains extension, on pourrait le supprimer du dépot et le gitignore, comme ça LMS fait ce qu'il veut avec mais ça embrouille pas outre mesure? 

> Pour simplifier le chemin (et éviter templates/bazar/templates), je ne suis pas contre, l'idée était d'avoir la même structure que dans les tools/monext/presentation mais je suis d'accord que c'est plus lisible
Justement, c'est pas la même structure :) Pour moi avoir la même structure ça veut dire
`custom/tools/monext/presentation/template/my-custom-template.tpl.html`
mais le chemin actuel n'a pas trop de sens IMHO :)

> je suis pour qu'il soit vide et facilement déployé avec un dépot git, mais je voudrais qu'il soit quand meme crée et présent dans le zip
Je pense que ça devrait le faire avec le gitkeep, je testerai !

2020-10-20 12:32 UTC, mrflos commented
> > Custom tools
> 
> Ok pour copier la totalité du tools ! c'est souvent utilisé?

Pas trop pour l'instant, mais j’espère que ca va le devenir!

> > Je me demande s'il ne serait pas mieux d'avoir un dossier custom/actions et un dossier custom/handlers/page pour mettre des actions spécifiques?
> 
> Je suis d'accord :) Eventuellement aussi un custom.css et un custom.js? sinon il faut modifier le squelette pour include ses propres fichiers css et javascript

Yes, pour info, ya déja la PageCss pour mettre du style css custom dans un wiki (avec gestion de l'historique), mais ta proposition d'avoir les fichiers `custom/custom.css` et `custom/custom.js` fait sens, comme ca tu maintiens un dépot avec toutes tes customs dedans. Ca vous irait les product owner?

> > dossier template à la racine
> 
> mmm, perso je trouve que ça embrouille, parce que des templates y'en a dans les tools/XXX/presentation/templates, dans les themes, dans le dossier racine templates, et dans custom/templates !! pourquoi le LMS met pas juste les templates dans le tools LMS? ou alors si ce dossier racine template est géré de manière automatique juste par certains extension, on pourrait le supprimer du dépot et le gitignore, comme ça LMS fait ce qu'il veut avec mais ça embrouille pas outre mesure?

A discuter, pour moi la nuance c'est que custom/templates c'est vraiment du sur mesure, alors que templates/ ca vient d'installateurs automatiques, et plutôt que d'avoir a fouiller chaque dossier tools, on ne cherche que dans templates/ par exemple , on pourrait avoir l'extension gogocarto, qui envoies les bons fichiers dans templates a l'install, et qui sera disponible pour {{bazarliste template=}} et si l'on veut changer un comportement, on pourra aller copier les fichiers dans custom/templates

> > Pour simplifier le chemin (et éviter templates/bazar/templates), je ne suis pas contre, l'idée était d'avoir la même structure que dans les tools/monext/presentation mais je suis d'accord que c'est plus lisible
> 
> Justement, c'est pas la même structure :) Pour moi avoir la même structure ça veut dire
> `custom/tools/monext/presentation/template/my-custom-template.tpl.html`
> mais le chemin actuel n'a pas trop de sens IMHO :)

oui.. mais du coup `templates/bazar` et `custom/templates/bazar/` ca passe, non?
> 
> > je suis pour qu'il soit vide et facilement déployé avec un dépot git, mais je voudrais qu'il soit quand meme crée et présent dans le zip
> 
> Je pense que ça devrait le faire avec le gitkeep, je testerai !
Ok cool!

2020-10-20 13:39 UTC, seballot commented
> on pourrait avoir l'extension gogocarto, qui envoies les bons fichiers dans templates a l'install, et qui sera disponible pour {{bazarliste template=}} et si l'on veut changer un comportement, on pourra aller copier les fichiers dans custom/templates

En effet, je comprend mieux merci !

> templates/bazar et custom/templates/bazar/ ca passe

Oui carrément !

2020-10-21 11:21 UTC, acheype commented
> A discuter, pour moi la nuance c'est que custom/templates c'est vraiment du sur mesure, alors que templates/ ca vient d'installateurs automatiques, et plutôt que d'avoir a fouiller chaque dossier tools, on ne cherche que dans templates/ par exemple , on pourrait avoir l'extension gogocarto, qui envoies les bons fichiers dans templates a l'install, et qui sera disponible pour {{bazarliste template=}} et si l'on veut changer un comportement, on pourra aller copier les fichiers dans custom/templates

Il me semble toutefois que ça serait bien d'améliorer ce comportement. Par exemple, pour le module LMS, il est nécessaire de lancer le handler update pour que update__ puisse copier les templates de `tools/lms/libs/bazar-templates` vers `templates/bazar/templates`. Mais en plus du fait que l'extension ne fonctionne pas jusqu'au moment où on lance l'update (améliorable en proposant l'update à l'installation de l'extension), on se retrouve avec des templates en double et notamment en dev c'est assez chiant de devoir maintenir les deux à jour.

Je proposerais qu'on se cale sur ce qui est fait pour les actions, handlers et formatters, c'est à dire d'avoir une variable `templates` dans `$GLOBALS['wiki']` qui liste les répertoires par ordre de priorité et qu'à chaque chargement d'une extension on rajoute à cette liste le `$pluginBase . 'presentation/formatters/` tel que c'est fait [ici](https://github.com/YesWiki/yeswiki/blob/de253ad44c5c92403b49493ad51874f912165ed7/includes/YesWiki.php#L2375). On peut même en profiter pour sortir le répertoire de presentation et le mettre au même niveau qu'action, handlers et formatters (perso, je trouverais cela plus logique).

Qu'en dites-vous ?

> Yes, pour info, ya déja la PageCss pour mettre du style css custom dans un wiki (avec gestion de l'historique), mais ta proposition d'avoir les fichiers custom/custom.css et custom/custom.js fait sens, comme ca tu maintiens un dépot avec toutes tes customs dedans. Ca vous irait les product owner?

C'est une super idée, car avec margot qui fait l'hunanimité aujourd'hui on a davantage besoin de rajouter du code css/js et que celui-ci puisse être versionné dans les projets spécifiques. Pour qu'on sache à quel projet appartiennent les `custom.css` et `custom.js`, ça serait bien de ne pas contraindre le nom à custom. Et si on chargeait tous les .js et .css du répertoire `custom` ? ou à la racine de custom/theme (en laissant les répertoires aux themes) ? ou dans un répertoire spécifique ?

2020-10-22 13:37 UTC, sylvainboyer commented on tools/bazar/libs/bazar.fonct.php
>          'templates/bazar/templates/fiche-'.$fiche['id_typeannonce'].'.tpl.html',
OK

2020-10-22 13:41 UTC, sylvainboyer commented
OK avec les remarques et propositions de @acheype

2020-10-22 13:47 UTC, gatienbataille commented
Hello, donc
Pour la partie que j'ai pigé (désolé suis vraiment qu'un pauvre user ;-) 
moi ce que j'aimerais :
 - que ce soit en effet clair de savoir où on doit déposer ses templates ou thèmes ou ... sur mesure pour qu'ils soient prioritaires sur ceux fournis par défaut => je peux pas vraiment me prononcer sur l'endroit idéal mais plus c'est simple mieux ça me va)
 - que ça soit rétrocompatible avec les wikis existants car c'est fort utilisé ces templates sur mesure
 - que l'on puisse encore mettre du html dedans même si c'est pas propre mais faudrait pas exclure les "non dév" qui essaient de bidouiller des templates car c'est ça le truc sympa de yeswiki : je peux essayer (et même parfois ça marche), je peux tenter d'être un peu autonome même si pas très "propre" !! 
>  Yes, pour info, ya déja la PageCss pour mettre du style css custom dans un wiki (avec gestion de l'historique), mais ta proposition d'avoir les fichiers custom/custom.css et custom/custom.js fait sens, comme ca tu maintiens un dépot avec toutes tes customs dedans. Ca vous irait les product owner?
euh oui...

2020-10-22 14:51 UTC, acheype commented
yep @gatienbataille, ce que tu aimerais est en phase avec ce qui se dessine. Notamment, pas de soucis avec la rétrocompatibilité car si j'ai bien compris sur les vieux wiki, puisqu'il n'y avait pas de répertoire custom, les templates étaient directement mis dans tools/bazar/presentation/templates. Au pire s'il on change `tools/bazar/presentation/templates` en `tools/bazar/templates`, il faudra juste déplacer les templates rajoutés (et pour bien faire, il faudrait dans ce cas les mettre dans `custom/templates`).

Par rapport à 
> que l'on puisse encore mettre du html dedans même si c'est pas propre mais faudrait pas exclure les "non dév" qui essaient de bidouiller des templates car c'est ça le truc sympa de yeswiki : je peux essayer (et même parfois ça marche), je peux tenter d'être un peu autonome même si pas très "propre" !!

Ce dont parlait @mrflos plus haut et qui n'est pas propre, c'est plutôt l'inverse : mettre du code "logique" et non de rendu dans le template. C'est quelque chose qui se produit souvent car les templates font en général plus que juste de l'affichage. C'est une bonne pratique de programmation de séparer les deux, 1) on prépare les données 2) on les affiche.
Ce qui m'amène à cette remarque : autant pour les templates utilisés dans des actions (ou handlers), par exemple `bazarliste`, on peut préparer les données et les transmettre au template avec `SquelettePhp`, autant quand on fait un template pour une fiche bazar précise, c'est bazar qui appelle le template et on ne peut alors pas faire cette préparation des données. Ca serait sympa donc sympa de trouver un mécanisme adapté...

2020-10-22 15:07 UTC, sylvainboyer commented
Attention, l'intérêt du comportement actuel de bazar est justement, faisant fi de l'orthodoxie MVC, de permettre à l'utilisateur (pas un vrai dév.) de pouvoir bidouiller et la préparation des données et leur affichage dans un seul endroit (c'est plus simple pour le non dév. à mon avis.
Sur un autre plan, j'avais, et j'ai toujours, en tête d'introduire du CSS grid dans les squelettes bazar pour offrir au moins des possibilités de réorganisation de la présentation des données.

2020-10-23 11:59 UTC, acheype commented
@sylvainboyer Oui, pour que les non dév puissent bidouiller leur template il faut laisser la possibilité de continuer à faire comme aujourd'hui. Mais ça n'empêche pas de proposer un système pour avoir des templates mieux organisés.
On pourrait comme tu en parles diviser un template en deux fichiers (1 pour la présentation, 1 pour la logique) mais comme toi j'ai peur que ça alourdisse. On pourrait proposer comme convention qu'une fonction `prepareData` (si elle existe) soit appelée par bazar juste avant le rendu du template. Ca pourrait encourager ceux qui ont le niveau de séparer la logique de la présentation. Qu'en pensez-vous ? D'autres idées ?

2020-10-24 14:27 UTC, seballot commented
Yop, j'ai avancé sur le sujet, vous pouvez voir la [nouvelle doc ici](https://github.com/YesWiki/yeswiki/blob/202ff7d8599eaa20ca9912e5148d439ab6d38c8b/docs/customize-your-wiki.md) : 

Pour faire court
- on peut maintenant dans le dossier custom mettre les même dossier que dans une extension (handler, actions, formatters, lang ...)
- les fichiers `custom\javascripts\custom.js` et `custom/styles/custom.css` sont chargé automatiquement si ils existent
- on peut ajouter des templates bazar dans `custom/templates/bazar`

Exemple : https://github.com/YesWiki/yeswiki-custom-code-example
Depuis la racine de yeswiki je peux lancer `git clone https://github.com/YesWiki/yeswiki-custom-code-example.git custom`
Et voilà !

Par rapport aux discussions précédentes
- pour les fichiers Js et Css, je pense que c'est plus simple de les appeler "custom.js|css". A priori si tu utilises un dépot, le dépot aura le nom du projet, donc ça devrait pas poser de soucis
- j'ai du supprimé le répo `custom` du dépot YesWiki, sinon on ne peut pas checkout dedans (on peut checkout uniquement dans un dossier vide)... 
- la discussion d'inclure ou non du code php dans les template bazar ne me semble pas liée à ce ticket. Je pense qu'il y a eu une mauvaise compréhension, moi je disais juste que je ne comprenais pas trop la logique du répertoire `custom/themes/tools/bazar/templates/fiche-5.tpl.html` (une extension dans un thème??). Mais peu importe, tous les anciens répertoires on été laissé pour la retro compatibilité :)

2020-11-04 18:16 UTC, acheype commented
Je vais recréer une autre branche qui part de celle-ci pour traiter les points que j'ai évoqué. C'est l'occasion de surfer sur cette vague de changements avec le gros boulot de refactoring bazar effectué par @srosset81 en ce moment.

Juste par rapport à custom.js|css @seballot : je vais tout de même rendre possible l'ajout de n'importe quel fichier css ou js qui est dans déposé dans  `/custom/styles` et `/custom/javascripts` car c'est bloquant pour notre thème jdn. On a en fait plusieurs javascripts supplémentaires dans themes/margot/javascripts (un pour le thème, un pour gérer les interractions avec humhub, et un troisième qui customize les schémas thinglink qu'on intègre). J'espère que tu n'as pas d'objection à cela ;)

2020-11-04 18:41 UTC, seballot commented
Yop ! merci pour les petites corrections :)
non pas d'objection à ça, mais tu sais que tu peux include d'autres fichiers css et javascript à partir de custom.css  (avec des include) et custom.js (avec des import), donc je pense pas que ce soit bloquant !

2020-11-04 22:58 UTC, acheype commented
@seballot ah oui, j'avais pensé aux includes css mais pas aux imports js !!!
je l'ai quand même fait, c'était pas compliqué et je trouve ça plus cohérent par rapport au fonctionnement existant (tous les js du répertoires themes/MONTHEME/javascripts sont automatiquement chargés).

2020-11-06 07:44 UTC, merged