[WIP] New FormManager
YesWiki/yeswiki pull request #542
Opened 2020-11-17 15:40 UTC by srosset81

2020-11-20 13:47 UTC, J9rem commented on tools/bazar/fields/BazarField.php
> +    protected const FIELD_DEFAULT = 5;
```suggestion
    protected const FIELD_DEFAULT = 5;
    protected const FIELD_LIST_LABEL = 6;
```
pour permettre de nous souvenir que le champ est déjà utilisé.

2020-11-20 13:48 UTC, J9rem commented on tools/bazar/fields/EntryListField.php
> +        $this->recordId = $values[self::FIELD_TYPE] . $values[self::FIELD_ID] . $values[6];
```suggestion
        $this->recordId = $values[self::FIELD_TYPE] . $values[self::FIELD_ID] . $values[self::FIELD_LIST_LABEL];
```

2020-11-20 13:50 UTC, J9rem commented on tools/bazar/fields/ListField.php
> +        $this->recordId = $values[self::FIELD_TYPE] . $values[self::FIELD_ID] . $values[6];
```suggestion
        $this->recordId = $values[self::FIELD_TYPE] . $values[self::FIELD_ID] . $values[self::FIELD_LIST_LABEL];
```
idem pour rester cohérent avec mon autre commentaire

2020-11-20 13:51 UTC, J9rem reviewed
Je me disais que nous pourrions introduire une constante aussi pour le champ numéro 6 utilisé par les listes ou équivalent

2020-11-20 16:07 UTC, srosset81 commented
> Je me disais que nous pourrions introduire une constante aussi pour le champ numéro 6 utilisé par les listes ou équivalent

Ah oui merci, je savais pas ce que c'était ce 6ème paramètre !

2020-11-20 16:13 UTC, J9rem commented
En fait, @seballot a fait un gros boulot d'identification des paramètres et de leur nom [à cet endroit : form-edit-template.js#L473](https://github.com/YesWiki/yeswiki/blob/doryphore/tools/bazar/presentation/javascripts/form-edit-template.js#L473) si ça t'aide

2020-11-27 12:42 UTC, mrflos requested changes
ya un dump qui traine!

2020-11-27 12:42 UTC, mrflos commented on tools/bazar/libs/bazar.fonct.php
> +            dump($forms);
oups

2020-11-28 05:55 UTC, seballot commented
Yop, petit commit du matin : j'ai utilisé des layout twig pour les templates

Ce qui est super avec twig, c'est que dès que t'utilises un chemin d'accès avec namespace, genre @bazar/XXX, et bien c'est customizable

Donc ça veut dire que si je créé le fichier `custom/templates/bazar/layouts/input.twig` et bien je peux changer la forme générale du formulaire (i.e. plutot que le label en col-md-3 je peux le mettre en full width par exemple)

2020-11-28 08:06 UTC, mrflos commented
d'ailleurs les col-md-3 sont bypassées par margot, faudrait il pas du coup les virer ?

2020-11-28 08:31 UTC, J9rem commented
> 
> 
> d'ailleurs les col-md-3 sont bypassées par margot, faudrait il pas du coup les virer ?
> Vire idéalement que le theme margot surgarge les templates par défaut de bazar pour faire un exemple?

D'autres sites utilisent d'autres thèmes avec Doryphore (comme le thème Colibris).
Même si ça n'est pas idéal, ne faudrait-il pas vérifier l'impact sur ces thèmes par exemple ?

2020-11-28 08:43 UTC, mrflos commented
> D'autres sites utilisent d'autres thèmes avec Doryphore (comme le thème Colibris).
> Même si ça n'est pas idéal, ne faudrait-il pas vérifier l'impact sur ces thèmes par exemple ?

C'est pour cela que je propose de faire un twig dans le theme margot, comme ca ca casse pas le reste, et ca ferait plus propre niveau balises et classes css utilisées

2020-11-28 08:45 UTC, seballot commented
La discussion sur margot et le layout input devrait se faire sur un autre ticket je pense ;)

Concernant ce ticket, j'ai fait d'autres améliorations, dis moi ce que t'en penses @srosset81 ?

concernant le nommage, je trouvait que `entryId` n'était pas approprié, pour moi entry id c'est l'id de l'entry... j'ai changé en `propertyName` (pas été super inspiré)

Egalement, concernant le nommage copié sur ReactAdmin, je suis pas super fan, voilà quelques autres pistes au cas ou :
renderField / **renderStatic** / renderDisplay / renderShow
**renderInput** 
formatInput / **formatValuesBeforeSave**
Mais bon c'est secondaire, ça me va aussi de garder le nommage actuel

2020-11-28 11:16 UTC, srosset81 commented
> concernant le nommage, je trouvait que `entryId` n'était pas approprié, pour moi entry id c'est l'id de l'entry... j'ai changé en `propertyName` (pas été super inspiré)

Oui effectivement `entryId` peut générer de la confusion. `propertyName` me semble mieux.

> Egalement, concernant le nommage copié sur ReactAdmin, je suis pas super fan, voilà quelques autres pistes au cas ou :
> renderField / **renderStatic** / renderDisplay / renderShow
> **renderInput**
> formatInput / **formatValuesBeforeSave**
> Mais bon c'est secondaire, ça me va aussi de garder le nommage actuel

OK pour changer à renderStatic et formatValuesBeforeSave :-)

2020-11-28 11:27 UTC, srosset81 commented on tools/bazar/fields/BazarField.php
> +    public function setEntry($entry)
Je ne crois pas que ce soit possible, ni désirable.
Les fields sont chargés une fois au chargement du formulaire. Mais le même objet formulaire peut être utilisé pour traiter plusieurs fiches. 
Il est donc préférable de ne pas lier le formulaire à la fiche.

2020-11-28 11:52 UTC, seballot commented on tools/bazar/fields/BazarField.php
> +    public function setEntry($entry)
ah ok j'avais pas compris le code dans ce sens ! je crois que j'y suis maintenant : on stocke l'object form dans la fiche elle même, donc en fait chaque fiche contient le même objet form c'est ça?
`$fichebazar1['form'] === $fichebazar2['form']` ?
ça fait un peu un truc chelou du coup le `$fichebazar['form']['prepared'][$i]->renderField($fichebazar['values']);`  mais forcément on arrive à ce genre de truc quand on utilise pas des objets !

Du coup plusieurs de mes changements sont pas super, car je stocke par example $value en attribut de classe... ça marche car l'éxecution est linéaire, mais ça pas super clean :

```php
$field = new BazarField(..)
$field->setEntry($entry1)
$field->render()
$field->value === $entry1->propertyName

$field->setEntry($entry2)
$field->render()
$field->value === $entry2->propertyName
```

J'ai fait ça car comme $entry n'est pas un object non plus, on galère à écrire du code propre. Et ça a permis de factoriser du code qui était dans chaque field

Du coup je sais pas trop, on laisse comme ça et je met des commentaires pour expliquer ou j'essaie de revenir à comme c'était avant sans entry et value comme variable d'instance ?

2020-11-28 14:44 UTC, srosset81 commented on tools/bazar/fields/BazarField.php
> +    public function setEntry($entry)
$value ne peut être stocké comme propriété de la classe malheureusement.

Tu pourrais en revanche avoir un getValue($entry), qui se baserait sur propertyName pour sélectionner la valeur dans la fiche.

2020-11-28 14:44 UTC, srosset81 commented on tools/bazar/fields/BazarField.php
> +    public function setEntry($entry)
Donc oui il faut revenir en arrière je crains...

2020-11-28 16:28 UTC, seballot commented on tools/bazar/fields/BazarField.php
> +    public function setEntry($entry)
ok c'est fait :)

2020-12-06 18:11 UTC, J9rem reviewed
J'ai ajouté des commentaires pour éviter de faire le rendu des champs si la valeur est vide. Il est possible de choisir de retourner `null` à la place de `''` même si je pense que par souci de compatibilité, la plupart des fonctions attendent une chaîne de caractère en appelant renderStatic

2020-12-06 18:11 UTC, J9rem commented on tools/bazar/fields/BazarField.php
> +        return $this->render("@bazar/fields/{$this->type}.twig", [
```suggestion
         return empty($this->getValue($entry)) ? '' : $this->render("@bazar/fields/{$this->type}.twig", [
```

Pour garder le même comportement qu'avant, je propose de ne pas faire le rendu pour les valeurs vides.

2020-12-06 18:11 UTC, J9rem commented on tools/bazar/fields/LabelField.php
> +        return $this->viewText . "\n";
```suggestion
        return empty($this->viewText) ? '' : $this->viewText . "\n";
```
idem par de retour pour les valeurs vides

2020-12-06 18:11 UTC, J9rem commented on tools/bazar/fields/TagsField.php
> +        }
```suggestion
```

2020-12-06 18:11 UTC, J9rem commented on tools/bazar/fields/TagsField.php
> +        ]);
```suggestion
        ]);
        } else {
            return null ;
        }
```
idem pas de rendu si vide

2020-12-06 18:11 UTC, J9rem commented on tools/bazar/fields/TextField.php
> +        return $this->render("@bazar/fields/text.twig", [
```suggestion
        return empty($this->getValue($entry)) ? '' : $this->render("@bazar/fields/text.twig", [
```
idem pas de rendu si vide

2020-12-06 18:11 UTC, J9rem commented on tools/bazar/fields/TextareaField.php
> +        switch($this->syntax){
```suggestion
if !empty($this->getValue($entry)) {
        switch($this->syntax){
```

2020-12-06 18:11 UTC, J9rem commented on tools/bazar/fields/TextareaField.php
> +        ]);
```suggestion
        ]);
    } else {
      return null ;
    }
```

2020-12-07 09:05 UTC, srosset81 commented
> J'ai ajouté des commentaires pour éviter de faire le rendu des champs si la valeur est vide. Il est possible de choisir de retourner `null` à la place de `''` même si je pense que par souci de compatibilité, la plupart des fonctions attendent une chaîne de caractère en appelant renderStatic

Est-ce que cela pose un problème ? Que la fonction renderStatic return null ou '', je n'ai pas l'impression que ça change grand chose.

2020-12-07 09:16 UTC, J9rem commented
> 
> 
> Est-ce que cela pose un problème ? Que la fonction renderStatic return null ou '', je n'ai pas l'impression que ça change grand chose.

Effectivement après une nuit de réflexion la concaténation de `null ` et d'une chaîne de caractère sera la même chose que la concaténation de `''`et de la même chaîne de caractère.
Totalement d'accord avec ta remarque

2020-12-07 15:28 UTC, J9rem commented on tools/bazar/fields/CheckboxEntryField.php
> +        $this->loadOptionsFromEntries();
Je remplacerais bien ```$this->loadOptionsFromEntries();``` par   ```$this->loadOptionsFromEntries()['label'];``` pour éviter de nous trimbaler le ```'label'```dans le reste du code sachant que nous n'avons pas besoin des autres informations du tableau.
Qu'en dis-tu ? @srosset81

2020-12-07 15:33 UTC, srosset81 commented on tools/bazar/fields/CheckboxEntryField.php
> +        $this->loadOptionsFromEntries();
Oui, je veux d'abord voir si les propriétés autres que `label` sont utilisées dans le code, si ce n'est pas le cas on pourra tout virer.

2020-12-08 15:47 UTC, mrflos reviewed
RIP tools/bazar/libs/formulaire/formulaire.fonct.inc.php , petit ange parti trop tôt...

2020-12-08 16:06 UTC, merged