fix remove all checkbox
YesWiki/yeswiki pull request #548
Opened 2020-11-23 14:30 UTC by J9rem

Problème :
impossible de vider complètement une checkbox ou checkboxfiche
Résolu par cette PR

A suivre @srosset81 pour tes modifications

2020-11-23 16:28 UTC, srosset81 requested changes

2020-11-23 16:28 UTC, srosset81 commented on tools/bazar/services/FicheManager.php
> +            }
Normalement ce type d'opérations (modification des données avant écriture dans BDD) est fait au niveau de `baz_requete_bazar_fiche`, qui a été bougé à l'intérieur du FormManager dans ma PR.
Je serai partant pour que tu identifie le problème à ce niveau-là, afin que ça puise ensuite être transféré sur la nouvelle PR.

2020-11-23 16:34 UTC, J9rem commented on tools/bazar/services/FicheManager.php
> +            }
En fait, le point clé est ici :
- c'est le seul endroit où il y a un array_merge entre les données précédentes et les données du formulaire
- quand il n'y a aucune checkbox sélectionnée, l'entrée de $data qui correspond à checkbox est vide où égale à `''`, sauf que array_merge va alors écraser cette valeur car il va considérer que c'est vide, ....

J'ai essayé plusieurs solutions et je trouve que c'est la plus élégante... mais je suis à l'écoute d'autres propositions.

2020-11-23 16:47 UTC, srosset81 commented on tools/bazar/services/FicheManager.php
> +            }
Ca reste quand même un hack, typiquement le genre de choses dont le code YesWiki est bourré, et qui rend la lecture du code presque impossible ;)

Il existe une solution: passer un nouveau paramètre `$previousData` à la fonction `baz_requete_bazar_fiche`. Et du coup dans la méthode `FicheManager::update`, passer le `$previousData` qu'on a à disposition. Par contre ne rien passer dans la méthode `FicheManager::create`. A partir de là, tu as tous les éléments pour faire quelque chose de propre.

2020-11-23 16:48 UTC, J9rem commented on tools/bazar/services/FicheManager.php
> +            }
Moi ça me va, j'y regarde demain ;-)

2020-11-23 17:10 UTC, J9rem commented on tools/bazar/services/FicheManager.php
> +            }
J'essaie de faire des tests et je me dis que ce serait plus sûr de créer une fonction privée dans la classe FicheManager qui est la classe qui possède les données.
Cette fonction ne serait appelée que par update.
J'ai mis HACK mais en fait, ça n'est peut-être pas un HACK mais une réparation.

La fonction pourrait s'appeler updateWithPreviousDate($data,$previousData,$replace)
ce qui donnerait 
`$data = updateWithPreviousDate($data,$previousData,$replace) ;`

en cherchant à vouloir l'ajouter à `baz_requete_bazar_fiche` je trouve que ça rend compliqué la lecture du code.

Mais si ce nouvel argument ne te semble pas fondé, alors je déplace dans `baz_requete_bazar_fiche`

2020-11-23 17:13 UTC, srosset81 commented on tools/bazar/services/FicheManager.php
> +            }
Sur la branche `refactor/form-manager`, la fonction `baz_requete_bazar_fiche` a été déjà remplacée par `FicheManager::formatDataBeforeSave`.

Je préférerai que tu limites le refactoring pour éviter les conflits de merge.

2020-11-23 18:21 UTC, mrflos commented
pendant que tu y es, si t'es chaud, ya #135 qui traine depuis ... ... 2014.
Ya pas d'urgence, mais comme c'est sur la meme thématique, ca serait bien que dans le cas d'une liste déroulantes non obligatoire, on puisse remettre a zero aussi.

2020-11-23 18:24 UTC, J9rem commented
> 
> 
> pendant que tu y es, si t'es chaud, ya #135 qui traine depuis ... ... 2014.
> Ya pas d'urgence, mais comme c'est sur la meme thématique, ca serait bien que dans le cas d'une liste déroulantes non obligatoire, on puisse remettre a zero aussi.

A oui, ce sera facile à faire.

2020-11-23 18:25 UTC, J9rem commented
Je pense que je vais finalement faire une PR sur la branche form-refacto pour simplifier les merges de @srosset81 .

2020-11-24 00:12 UTC, acheype commented on tools/bazar/services/FicheManager.php
> +            }
Je n'avais pas vu la PR et justement je voulais réagir à ce bout de code, je confirme c'est bel et bien un hack ! ;)

Si on peut également éviter que soit fait un traitement particulier pour 'checkbox', ce serait plus propre. Déjà ça me semble possible en faisant en sorte que ce soit le champ checkbox qui initialise sa valeur à '' quand il y a aucun élément de sélectionner (c'est certainement ce qui était fait avec le mode tags car cela fonctionnait). Mais si update pouvait marcher avec des clés supprimées, ça serait encore mieux.

Le truc que je n'arrive pas à saisir, c'est pourquoi update à deux modes, un en 'replace' et un autre qui merge avec les anciennes données. Vous sauriez me dire l'utilité, ce n'est pas très courant dans une couche DAO ?

2020-11-24 07:52 UTC, J9rem commented on tools/bazar/services/FicheManager.php
> +            }
J'ai trouvé comment faire, il me reste plus qu'à l'écrire, ....

2020-11-24 09:30 UTC, acheype commented on tools/bazar/services/FicheManager.php
> +            }
Suis-je le seul à trouver bizarre ce merge pour l'update ? le mode $replace = true n'est en plus jamais appelé.
les champs 'createur', 'date_creation_fiche', 'firstime', 'statut_fiche' sont ensuite gérés par baz_requete_bazar_fiche (aucun code spécifique à un type de champ n'est d'ailleurs introduit dans cette fonction).

@mrflos, @srosset81, vous auriez une idée de la raison de ce merge ?

2020-11-24 10:34 UTC, J9rem commented on tools/bazar/services/FicheManager.php
> +            }
AH oui effectivement enlever le array_merge serait très pratique car ça résoudrait les soucis pour

2020-11-25 08:56 UTC, J9rem commented
je migre vers https://github.com/YesWiki/yeswiki/tree/fix-remove-all-checkbox-refacto

2020-11-25 08:56 UTC, closed without merging