Add anchors management for yeswiki links and simplify
YesWiki/yeswiki pull request #594
Opened 2021-01-03 19:09 UTC by acheype

Suite de https://github.com/YesWiki/yeswiki/pull/593.

J'ai surtout fait en sorte que les ancres soient gérées directement depuis les fonctions de liens et qu'elles ne passent pas en bidouille pour un lien classique.
J'ai gardé le \S, c'était en effet une bonne idée, cela simplifie et ça n'a pas de conséquence sur le reste.
J'ai simplifié au niveau des regexps de Constants, j'ai factorisé extractLinkParts et generateLink et maintenant les liens qui n'ont pas de tag sont reconnus de partout en tant que page courante.

@mrflos Tu avais donné le choix d'utiliser ? ou & pour passer aux paramètres dans l'url. Tu y tiens ?
Je ne suis pas fan dès le départ de laisser ces deux possibilités, car j'ai peur que ça embrouille de voir les deux utilisations. Pour moi, c'est plus clair de laisser le Tag + # pour mettre une ancre + ? pour mettre un paramètre et & pour les autres paramètres : ça respecte la logique des urls  internet. Et on risque en plus de passer un de ces jours à des urls plus classiques avec les @Route de symfony (si on préfère, bref on verra).
Je voulais à la base laisser les 2 possibilités et d'abord t'en parler mais ça m'a bloqué pour avancer, donc je l'ai supprimer.
En effet maintenant que le tag vide renvoie la page courante, quand on écrit `?Bazar&param1=1&param2=2`, on n'aurait pas pu dissocier s'il on voulait la page Bazar avec 2 paramètres, ou la page courante avec le paramètre Bazar sans valeur + param1 et 2 avec valeurs. Maintenant c'est cette dernière option qui est reconnue.

J'ai aussi rajouté la possibilité pour href d'avoir comme ci-dessus des paramètres sans valeur car [ces paramètres sont parfaitement valides](https://stackoverflow.com/a/14194196).

Voici les différents cas testés :
```
[[Bazar/edit&tutu=1&titi=2 Bazar/edit&tutu=1&titi=2]]
[[https://yeswiki.test/?Bazar/edit&tutu=1&titi=2 https://yeswiki.test/?Bazar/edit&tutu=1&titi2=2]]
[[?Bazar/edit&tutu=1&titi=2 ?Bazar/edit&tutu=1&titi=2]]
[[#ancre #ancre]]
[[chemin/fichier.html chemin/fichier.html]]
[[BazaR#toto BazaR#toto]]
```

Et pour le chemin relatif (c'était déjà le cas pour https://github.com/YesWiki/yeswiki/pull/593), ça ne fonctionne pas. En effet, `chemin/fichier.html` est détecté en tant que tag : chemin et method : fichier.html.
Par contre `/files/monpdf.pdf` est détecter en tant que lien classique (car plusieurs /), mais du coup ça marche que sur les wiki qui ne sont pas dans un sous-répertoire...
A voir si c'est important mais s'il on veut, il y a toujours la possibilité de détecter les urls classiques qui commencent par /, et les réécrire en base_url + l'url...

2021-01-03 19:41 UTC, mrflos commented
J'aurais préféré qu'on en parle avant, car je ne suis pas très chaud pour ces modifications...  

Si j'avais ajouté la possibilité de faire des urls courtes avec ? ou & , c'était car cela me parait bien plus simple pour l'usager du wiki de pouvoir copier/coller un bout d'url d'un wiki et que cela fonctionne dans tous les cas..  

Pour l'ajout d'un param dans la méthode href, c'est vraiment périlleux, c'est utilisé par une vingtaine d'extension en plus du cœur, pour gérer un cas à la marge (les ancres) et qui marchait avec ma précédente version sans avoir à modifier tout le code.

De ce que j'ai vu du code, ya des trucs qui ne doivent assurement pas marcher comme dans includes/YesWiki.php ligne 414: 
` return $tag . ($anchor ? '#' . $anchor : '') . ($method ? '/' . $method : '');` ('ancre avant le handler?).  

Bref je comprends pas pour tu as passé tant de temps a réparer un truc qui n'était pas cassé...

2021-01-04 10:17 UTC, acheype commented
Il y avait tout de même l'ancre rajouté à un tag qui ne fonctionnait pas : `[[BazaR#toto BazaR#toto]]` + le fait de passer l'ancre dans le tag pouvait parfois poser problème (par exemple, le tracking link ne fonctionnait plus qd l'ancre était spécifiée) et rendait ces cas spécifiques difficilement compréhensible dans le code.
Pour moi, ça fait partie de refactoring qui est nécessaire pour qu'on ait des fonctionnements plus uniformes au sein de YesWiki mais oui j'aurais peut-être dû t'en parler... pas toujours évident d'estimer quand c'est nécessaire, surtout quand ça reste en PR et que ça reste bonifiable.

On peut peut-être prendre le temps pour s'appeler quand on a moment ?

Sinon, c'est vrai que ça modifie href qui est utilisé de partout mais il y a pas tant de cas où elle est appelée avec l'ensemble de ses paramètres. Et on peut toujours mettre anchor en dernier argument de fonction pour pas qu'il y ait de refacto.
Mais j'avais déjà dû modifier Link (moins utilisé mais tout de même), donc il y a déjà un passage sur les extensions à faire au cas où c'est utilisé. Donc pourquoi ne pas pas en profiter pour changer les appels concernés à href aussi...

Pour le ? et &, on peut le rajouter comme tu l'avais fait en spécifiant [?&] dans constants.php. Ca peut permettre d'utiliser à la fois & et ? pour débuter les paramètres. C'est juste qu'on ne pourra pas utiliser le ? en début car cela permet d'appeler la page courante avec des paramètres spécifiques.

Pour miniHref, pour le cas où on a un handler qui se sert des ancres, il faudrait en effet mettre l'ancre après le handler.

2021-01-27 16:02 UTC, J9rem requested changes

2021-01-27 16:02 UTC, J9rem commented on includes/YesWiki.php
> +    public function Link($tag, $method = null, $params = null, $anchor = null, $text = null, $track = 1, $forcedLink = false)
```suggestion
    public function Link($tag, $method = null, $params = null, $text = null, $track = 1, $forcedLink = false, $anchor = null)
```
c'était pas plus simple de faire cette modification et de ne pas toucher au code dans tous les autre fichiers (surtout que la fonction Link est un peu utilisée par tout le monde).
Par souci de rétrocompatibilité, je m'oppose à la modification de l'ordre des paramètre de Link sachant qu'il est assez facile de faire autrement.

2022-08-25 10:44 UTC, closed without merging