Refacto getAllParameters, baz_rechercher, displayResultsList
YesWiki/yeswiki pull request #608
Opened 2021-01-20 14:13 UTC by srosset81

### Changements importants

- Les actions peuvent maintenant définir une méthode `formatArguments` qui permet de définir les arguments par défaut, et aussi de les définir en fonction des paramètres $_GET. C'était nécessaire pour se débarasser de `getAllParameters`, mais il faudra encore voir pour améliorer ça.
- Les actions peuvent maintenant appeler d'autres actions, via la méthode `callAction`. On est donc proche de la solution proposée par Adrien https://github.com/YesWiki/yeswiki/issues/558, sans pour autant que cela soit généralisé. C'était nécessaire pour gérer l'interaction entre l'action `bazar` et l'action `bazarliste`. Cela permet aussi de facilement "rediriger" vers une autre action (comme `bazarcarto` vers `bazarliste`) et éviter de la duplication de code.

### Ce qui n'est pas réglé (known bugs)

- `BazarListeExterneAction` ne marchait pas. Il charge maintenant les fiches, mais il affiche la template interne.
- `__WidgetHandler` n'affichait plus les facettes. Les facettes s'affichent maintenant mais il y a des problèmes d'affichages et, quand on en sélectionne une, le lien de l'iframe ne se mets pas à jour.

2021-01-25 15:15 UTC, J9rem commented
J'ai fait un commit après échange avec @srosset81 pour mes propositions d'amélioration

2021-01-25 15:37 UTC, J9rem requested changes, later dismissed
bazarliste ne fonctionne plus avec le template `map` dans ma configuration.
et calendrire.tpl.html présente de nombreux warnings pour des index inconnus

2021-01-25 15:37 UTC, J9rem commented on tools/bazar/actions/BazarCartoAction.php
> +        $color = $_GET['color'] ?? $arg['color'];
```suggestion
        $color = $_GET['color'] ?? $arg['color'] ?? null;
```
pour éviter des warnings

2021-01-25 15:43 UTC, J9rem commented
Il y a aussi des warnings avec l'index inconnu 'semantic' dans EntryControllerL66 et 'message' L132
Alors que c'est warnings n'existe pas sur la branche Doryphore, .. y a-t-il quelque chose de différent ?

2021-01-25 15:56 UTC, J9rem commented
bazar iframe ne fonctionne pas très bien plusieurs templates car il manque certains paramètres par défaut comme color.
Ils ne sont plus initialisé par défaut comme avant avec la valeur du fichier de config, ... même quand ça n'est pas pour la carte.
Est-ce que @srosset81 tu vois de quoi je veux parler ?

2021-01-25 16:00 UTC, srosset81 commented
> bazarliste ne fonctionne plus avec le template `map` dans ma configuration.

Je crois que ce commit doit fixer le problème https://github.com/YesWiki/yeswiki/pull/608/commits/6f89c2a9cb7aa1a7f4cc42be93c58f7e4b1f1140

2021-01-25 16:02 UTC, J9rem commented
> 
> 
> > bazarliste ne fonctionne plus avec le template `map` dans ma configuration.
> 
> Je crois que ce commit doit fixer le problème [6f89c2a](https://github.com/YesWiki/yeswiki/commit/6f89c2a9cb7aa1a7f4cc42be93c58f7e4b1f1140)

Bien chez moi ça ne fonctionne pas non plus dans les deux cas, je veux dire qu'il n'y a pas de rendu de la carte

2021-01-25 16:03 UTC, srosset81 commented
> > Je crois que ce commit doit fixer le problème [6f89c2a](https://github.com/YesWiki/yeswiki/commit/6f89c2a9cb7aa1a7f4cc42be93c58f7e4b1f1140)
> 
> Bien chez moi ça ne fonctionne pas non plus dans les deux cas, je veux dire qu'il n'y a pas de rendu de la carte

OK je regarderai plus tard. La carto marchait bien pour moi.
Tu peux donner le code que tu utilises ?

2021-01-25 16:05 UTC, J9rem commented
> 
> 
> > > Je crois que ce commit doit fixer le problème [6f89c2a](https://github.com/YesWiki/yeswiki/commit/6f89c2a9cb7aa1a7f4cc42be93c58f7e4b1f1140)
> > 
> > 
> > Bien chez moi ça ne fonctionne pas non plus dans les deux cas, je veux dire qu'il n'y a pas de rendu de la carte
> 
> OK je regarderai plus tard. La carto marchait bien pour moi.
> Tu peux donner le code que tu utilises ?

Le code de la page par défaut ?CartoAnnuaire
```
{{bazarliste id="1" template="map.tpl.html" height="800px" zoom="6"}}
```

2021-01-26 09:30 UTC, J9rem commented
Bon j'ai beau regardé, il y a des choses à migrer dans formatArguments depuis BazarCarto vers BazarListe,
en particuliers, tout ce qui concerne 'color' 'colorfiled' 'icon' 'iconfield' car ce sont des paramètres qui sont utilisés par de nombreux templates et pas uniquement carto.
Ensuite, dans l'ancien bazar.fonct, certains champs comme 'color' étaient initialisés avex `$wiki->GetParameter('color')`  et pas dans ce que tu propose, ...

en fait, il y a tellement d'endroits à corriger, que je pense que tu irais plus vite que moi pour les retrouver dans le code que tu as proposé @srosset81 qu'en dis-tu ?

2021-01-26 09:45 UTC, srosset81 commented
> en particuliers, tout ce qui concerne 'color' 'colorfiled' 'icon' 'iconfield' car ce sont des paramètres qui sont utilisés par de nombreux templates et pas uniquement carto.

Merci pour les infos. Tous ces champs étaient définis dans `getAllParameters_carto` donc j'avais aucune idée qu'ils étaient utilisés par d'autres templates. :-P Je vais les déplacer dans BazarListeAction.

2021-01-27 09:00 UTC, J9rem commented
@srosset81 je viens de faire un commit qui semble résoudre tous les soucis.
qu'en dis-tu ?

2021-01-28 10:05 UTC, J9rem commented
@srosset81 
# Liste des tests

## BazarAction

| Code | Test |
|:-|:-|
|`{{bazar}}`|OK|
|`{{bazar voirmenu="0"}}`|OK|
|`{{bazar}}` + `GET &vue=consulter&action=recherche&id=1`|OK|
|`{{bazar}}` + `GET &vue=saisir&action=saisir_fiche&id=1`|OK|
|`{{bazar}}` + `GET &vue=formulaire&action=new`|OK|

## BazarListeAction

### templates standard

| Code | Test |
|:-|:-|
|`{{bazarliste}}`|**NON OK** _non bloquant_ (1) |
|`{{bazarliste id="1"}}`| OK |
|`{{bazarliste id="1,2"}}`| OK |
|`{{bazarliste id="1" template="liste_accordeon"}}`| **NON OK** _bloquant_ (2)|
|`{{bazarliste id="1" template="liste_accordeon.tpl.html"}}`| OK |
|`{{bazarliste id="1"}}`+ `GET &template=liste_accordeon.tpl.html` | OK |
|`{{bazarliste}}`+ `GET &id=3&template=blog.tpl.html` | OK |
|`{{bazarliste}}`+ `GET &id=2&template=calendar.tpl.html` | OK |
|`{{bazarliste}}`+ `GET &id=2&template=agenda.tpl.html` | OK |
|`{{bazarliste}}`+ `GET &id=1&template=annuaire_alphabetique.tpl.html` | OK |
|`{{bazarliste}}`+ `GET &id=1&template=carousel.tpl.html` | OK |
|`{{bazarliste}}`+ `GET &id=1&template=damier.tpl.html` | **NON OK** _bloquant_ (3) |
|`{{bazarliste}}`+ `GET &id=1&template=gogomap.tpl.html` | **NON OK** _non bloquant_ (4) |
|`{{bazarliste}}`+ `GET &id=2&template=liste_liens_date.tpl.html` | **NON OK** _bloquant_ (5) |
|`{{bazarliste}}`+ `GET &id=2&template=liste_liens.tpl.html` | OK |
|`{{bazarliste}}`+ `GET &id=1&template=map.tpl.html` | OK |
|`{{bazarliste}}`+ `GET &id=1&template=material-card.tpl.html` | **NON OK** _bloquant_ (6) |
|`{{bazarliste}}`+ `GET &id=3&template=news.tpl.html` | **NON OK** _bloquant_ (7) |
|`{{bazarliste}}`+ `GET &id=1&template=photobox.tpl.html` | OK |
|`{{bazarliste}}`+ `GET &id=2&template=timeline.tpl.html` | **NON OK** _bloquant_ (8) |
|`{{bazarliste}}`+ `GET &id=2&template=trombinoscope.tpl.html` | OK |
|`{{bazarliste}}`+ `GET &id=2&template=widget.tpl.html` | **NON OK** _bloquant_ (9) |

(1) il semblerait que dans EntryManager autour du code  
```
		// On limite au type de fiche
        if (!empty($params['formsIds'])) {
```
il n'y ait pas de requête pour ne récupérer que les fiches avec `id_typeannonce` présent (même sans faire de tri sur id). Et donc ça pose problème dans la suite.

(2) il n'y a pas ajout de `.tpl.html`.
(3) `Undefined index: bf_bouton in \tools\bazar\presentation\templates\damier.tpl.html on line 193`
=> ajouter bf_bouton dans les params
(4) peut-être faut-il ajouter un aiguillage comme map.tpl.html pour utiliser `BazarCartoAction`
(5) `Parse error: syntax error, unexpected '<', expecting end of file in tools\bazar\presentation\templates\liste_liens_date.tpl.html on line 41`
(6) `Notice: Undefined index: bf_baseline in \tools\bazar\presentation\templates\material-card.tpl.html on line 87`
=> ajouter bf_baseline dans les params
(7) `Notice: Undefined index: date in \tools\bazar\presentation\templates\news.tpl.html on line 23`
=> ajouter 'date' dans les params ou message d'erreur si non définit
(8) `Notice: Undefined index: listeListeTailleImage in \tools\bazar\presentation\templates\timeline.tpl.html on line 41`
`Notice: Undefined index: texte in \tools\bazar\presentation\templates\timeline.tpl.html on line 66`
=> ajouter texte et listeListeTailleImage dans les params
(9) rien ne s'affiche (même pas un message d'erreur)


### templates https://github.com/YesWiki/templates-bazar

non testés

## BazarCartoAction


| Code | Test |
|:-|:-|
|`{{bazarcarto}}`|**NON OK** _non bloquant_(1) |
|`{{bazarcarto}}` + `GET &id=1` | OK |
|`{{bazarcarto}}` + `GET &id=1&template=gogomap.tpl.html` | **NON OK** _non bloquant_(2) |

(1) `Warning: htmlspecialchars() expects parameter 1 to be string, array given in \tools\bazar\libs\bazar.fonct.php on line 990`
(2) affichage de la carte mais pas des points (le problème semble déjà présent auparavant) => issue à créer

## MapAction

| Code | Test |
|:-|:-|
|`{{map id="1"}}`| OK |

## CalendrierAction

| Code | Test |
|:-|:-|
|`{{calendrier id="2"}}`| **NON OK** _non bloquant_(1) |

(1) affichage en semaine ne fonctionne pas (le problème semble déjà présent auparavant) => issue à créer

## BazarUserPageAction

| Code | Test |
|:-|:-|
|`{{bazaruserpage}}` + `GET &id=1,2,3`| OK |

## BazarIframeHandler

| Code | Test |
|:-|:-|
|`?BacASable/BazarIframe`| **NON OK** _non bloquant_(1) |
|`?BacASable/BazarIframe&id=1`| OK |
|`?BacASable/BazarIframe&id=1,3`| OK |

(1) code d'erreur : `Identifiant de la fiche non indiqué.` alors qu'on s'attendrait à `Identifiant de forumalaire "id" manquant.`

2021-01-29 11:15 UTC, mrflos commented
Il est marqué comme pret, mais en vue des résultats de tests j'attends encore pinguez moi @srosset81 et @J9rem si besoin de merger

2021-01-29 11:16 UTC, J9rem commented
> 
> 
> Il est marqué comme pret, mais en vue des résultats de tests j'attends encore pinguez moi @srosset81 et @J9rem si besoin de merger

Il y a du travail encore, ....

2021-01-31 20:00 UTC, J9rem commented
bon à part pour le template timeline et pour le template widget pour lesquels je n'ai pas encore approfondi l'erreur, les autres erreurs ne sont plus bloquantes et ne sont pas dues au refacto.

@mrflos Je pense que nous pouvons fusionner la branche.
Les petits bugs qui apparaitront ne seront pas graves.

Qu'en penses-tu @srosset81 ?

2021-01-31 20:02 UTC, J9rem approved these changes
je pense que la fusion ne provoquera pas de gros bugs et nous pourrons les détecter à l'usage.

2021-02-01 06:48 UTC, mrflos requested changes

2021-02-01 06:48 UTC, mrflos commented on tools/bazar/actions/BazarListeAction.php
> -
attention ya des templates autres que la carto qui utilisent les icones et couleurs, il faut ces parametre pour bazarcarto, bazarliste  et bazarcalendar

2021-02-01 06:48 UTC, mrflos commented on tools/bazar/actions/BazarListeAction.php
>              'filtercolsize' => $GET['filterposition'] ?? $arg['filterposition'] ?? '3',
SGET => $_GET

2021-02-01 13:48 UTC, J9rem commented on tools/bazar/actions/BazarListeAction.php
> -
C'est bon c'est remis dans BazarListeAction

2021-02-01 15:11 UTC, J9rem commented on tools/bazar/actions/BazarListeAction.php
>              'filtercolsize' => $GET['filterposition'] ?? $arg['filterposition'] ?? '3',
corrigé

2021-02-02 08:56 UTC, srosset81 commented
> bon à part pour le template timeline et pour le template widget pour lesquels je n'ai pas encore approfondi l'erreur, les autres erreurs ne sont plus bloquantes et ne sont pas dues au refacto.
> 
> @mrflos Je pense que nous pouvons fusionner la branche.
> Les petits bugs qui apparaitront ne seront pas graves.
> 
> Qu'en penses-tu @srosset81 ?

OK pour moi :-)

2021-02-03 08:51 UTC, mrflos approved these changes

2021-02-03 08:52 UTC, mrflos commented
ok pour moi aussi!

2021-02-03 11:52 UTC, merged