fix empty field acl in forms and bazarfields
YesWiki/yeswiki pull request #631
Opened 2021-01-29 11:32 UTC by J9rem

Bon je ne suis vraiment pas sûr d'avoir trouvé le meilleur endroit pour ce correctif.

Le problème : un formulaire peut avoir un template avec des champs readACL et writeACL vident.
Si le formulaire est modifié, c'est résolu par le javascript de l'édition des formulaires.

Toutefois, lors de la migration cercopitheque vers doryphore, OU vieux doryphore ou install par défaut, ces champs sont vides :
conséquences : il n'y a pas d'affichage des données car checkACL aimerait trouver une chaîne non vide.

1. @srosset81 es-tu OK avec la proposition de modifier le code à cet endroit ?
2. @mrflos est-ce que tu es d'accord avec le choix de récupérer les valeurs par défaut pour default_read_acl et default_write_acl normalement réservés pour les pages ?

A priori ça pourrait résoudre le souci d'oncletom.

_Je peux me charger de la fusion nettoyage de la branche etc une fois les revues validées._

2021-01-29 11:36 UTC, J9rem commented
en rapport avec #588

2021-01-29 12:30 UTC, mrflos commented
pour le default des droits des champs si non présent, je le mettrai plutot à * si pas précisé, c'est plutôt ca le comportement d'avant (vide = *).

2021-01-29 12:35 UTC, mrflos requested changes, later dismissed
je serai plutot pour mettre ouvert `*` par défaut en écriture et lecture pour les champs sans l'info, pour ne pas changer le comportement d'avant, et pour ne pas faire dépendre des droits d'acces aux pages.

2021-01-29 12:35 UTC, mrflos commented on tools/bazar/services/FormManager.php
> +                if (true /*function_exists($tablignechampsformulaire[self::FIELD_TYPE])*/) {
ca c'est trop ancien monde ;)

2021-01-29 12:35 UTC, mrflos commented on tools/bazar/services/FormManager.php
> +                        }
plutot `*` selon moi

2021-01-29 12:37 UTC, oncletom commented
Ça fonctionne en étant guest avec cette branche :-)

2021-01-29 12:37 UTC, J9rem commented on tools/bazar/services/FormManager.php
> +                if (true /*function_exists($tablignechampsformulaire[self::FIELD_TYPE])*/) {
oui mais j'ai pas touché, j'aime bien les marques de l'histoire :-)

2021-01-29 12:42 UTC, J9rem commented
Avec le dernier commit, j'ai déplacé les modifications depuis `parseTemplate` vers `prepareData`.
Ca me parait plus cohérent avec la philosophie du code.

J'ai aussi défini deux nouveaux champs 'prepared' `read_acl`et `write_acl` pour que l'Entrycontroller puisse les utiliser pour la rétrocompatibilité.

J'ai aussi mis à jour un test d'ACL pour la lecture des champs pour les templates custom.
J'ai aussi remis en place le test d'ACL pour l'écriture d'un champ (retrocompatibilité) il avait disparu (mais pas encore testé).

Enfin, j'ai mis le par défaut à `*` comme tu l'as proposé @mrflos

2021-01-29 12:47 UTC, acheype commented
Chouette d'avoir trouvé d'où ça venait. Cela m'interroge par contre en effet sur l'endroit où corriger ce soucis.

Ne serait-ce pas beaucoup plus simple d'ajouter le cas de chaîne vide à CheckACL ?

2021-01-29 13:07 UTC, J9rem commented
> 
> 
> Chouette d'avoir trouvé d'où ça venait. Cela m'interroge en effet sur l'endroit où corriger ce soucis.
> 
> Ne serait-ce pas beaucoup plus simple d'ajouter le cas de chaîne vide à CheckACL ?

J'y ai réfléchi ET je me suis dit que si CheckACL reçoit une chaîne vide, ... il ne doit pas dire que c'est OK car la chaîne vide correspond au comportement par défaut. Sauf que celui-ci dépend de si c'est en écriture, en lecture, si c'est un champ bazar, ...etc, ...

 et donc chaîne vide = false me parait normal.
 
 Charge selon à chaque controller (ou chose équivalente) de passer le bon paramètre (comme'*') selon les cas

2021-01-29 13:58 UTC, oncletom commented
Ce qui m'étonne c'est que selon le contexte, le rendu était différent (OK sur `{{bazarliste}}`, pas OK si appel à l'API uniquement). Vous y voyez plus clair à ce niveau ?

2021-01-29 14:09 UTC, J9rem commented
> 
> 
> Ce qui m'étonne c'est que selon le contexte, le rendu était différent (OK sur `{{bazarliste}}`, pas OK si appel à l'API uniquement). Vous y voyez plus clair à ce niveau ?

est-ce que si tu refais le test sur un wiki tout neuf (c'est-à-dire avec des read acl et write acl vides pour les fields) tu n'as plus le souci ?
(je n'ai pas testé l'api, je ne comprends toujours pas comment l'utiliser)

2021-01-29 21:08 UTC, acheype commented
j'ai mis du temps à comprendre que vous parliez en fait des acls sur les champs (merci jerem pour tes précisions en off)...

du coup, vu que je connaissais pas mal le sujet avec mon cassage de dent pendant le dernier sprint pour faire fonctionner les acls write, et que je me rappelais que ça fonctionnait bien à ce moment là avec une chaîne vide, je comprenais pas pourquoi il fallait tant de code pour ça.

Le soucis venait uniquement de l'acl en lecture. C'était juste qu'il manquait une condition dans le cas où le champ était représenté par un bazar field : si l'acl était vide, il ne fallait pas faire le test CheckACL.

Cf cette [PR](https://github.com/YesWiki/yeswiki/pull/633).

2021-02-01 13:36 UTC, J9rem commented
Je propose avec cette PR et le dernier commit de faire une fusion sur la PR #633.

Pour les tests d'écriture ou de lecture,
à chaque fois, d'abord on teste si c'est un BazarField, 
- si c'est le cas, on utilise les méthodes de BazarField
- sinon, on vérifie les accès puis on appelle la fonction

Pour la fonction, un champ vide, c'est qu'il n'a pas été préparé (erreur normalement).
Sinon, le form_manager définit le comportement par défaut pour les champs vides (et non l'entry controller).

Pour les BazarField, tester le field[11] n'est pas suffisant car, le BazarField peut très bien restreindre les accès en lecture aux administrateurs :
```
public fonction getReadAccess()
{

}
```

2021-02-02 19:55 UTC, acheype commented
Vu que tu as mergé les deux branches, j'ai regardé à nouveau et je me permets de faire une réponse détaillée.

Merci pour l'explication de BazarField, en effet mieux vaut ne pas factoriser comme je l'avais fait pour le cas où un BazarField redéfinit son `getReadAccess()`.
Tu as eu raison de modifier également la fonction `getValuesForCustomTemplate`, le test sur l'acl en lecture n'était fait que pour le BazarField et non plus pour les anciens champs (de mémoire, ça fonctionnait bien avant le refacto).
Et encore tu as bien fait de corriger `getRenderedInputs`, car contrairement à ce que j'avais dit il y avait aussi l'acl en écriture qui n'était pas pris en compte pour les anciens champs (avant l'équivalent de `$field->renderInputIfPermitted($entry)` était systématiquement appelé).

Je trouve aussi chouette que tu ais rajouté les attributs 'read_acl' et 'write_acl' aux anciens champs car on retrouve bien ces attributs à tous les champs et ça évite de passer par les moches ugly `[11]` ou `[12]`.

Mais pour moi le correctif ne devrait pas se faire en fixant une valeur par défaut dans FormManager, c'est pour cela que j'ai proposé une autre façon de faire le fix et je pensais au départ que tu étais du même avis puisque tu as débuté ce ticket avec "Bon je ne suis vraiment pas sûr d'avoir trouvé le meilleur endroit pour ce correctif.".
S'il n'y a pas d'autres solutions pourquoi pas, mais je trouve cela plus logique que ça soit fait directement là où on vérifie si le champ est accessible (autrement dit c'est la fonction qui se charge des cas particuliers). Cela évite aussi à un dev en regardant le code de ne pas comprendre comment est traité ce cas.
C'est d'ailleurs ce qui était fait jusque là (bon vu le code parfois de yeswiki, ce n'est pas un argument ;)), et pour l'acl en écriture on a toujours (même dans cette branche) le traitement de ce cas particuler qui est fait dans  `$field->renderInputIfPermitted($entry)`.

Pour montrer ce qui pour moi serait un mixte idéal des deux PR, j'ai fait un commit où je suis allé un cran plus loin : le test de l'acl en lecture n'est plus fait dans EntryController mais au niveau de FieldBazar : `$field->renderStaticIfPermitted($entry)`.
Il y aura toujours possibilité d'ajuster.

2021-02-02 20:18 UTC, J9rem commented
Super cool ton commit @acheype .
Tu proposes un réelle et belle amélioration de ce que j'avais initié.
Merci.
Ça me va parfaitement.

@acheype si OK pour toi, n'hésite pas à faire une fusion de cette branche sur la branche de la PR #633 pour faciliter la fusion finale vers Doryphore par Florian ou nous si @mrflos tout est OK pour toi.

2021-02-03 03:48 UTC, oncletom commented on tools/bazar/fields/BazarField.php
> +    protected function renderStatic($entry)
Je vois cette même méthode en `public` dans d'autres fields (genre, [`DateField.php`](https://github.com/YesWiki/yeswiki/blob/9ea98ba587c116e04304cce907882066ceed6988/tools/bazar/fields/DateField.php#L56). Est-ce que ça a un lien/impact de mixer `protected` / `public` ? ?

2021-02-03 07:10 UTC, closed without merging

2021-02-03 07:26 UTC, acheype commented on tools/bazar/fields/BazarField.php
> +    protected function renderStatic($entry)
Bien vu ! J'avais justement remarqué cela en écrivant la correction et je me suis dis autant ne pas trop mélanger les sujets et en parlé dans un deuxième temps.
C'est également le cas pour `renderInput` qui est `protected` tandis que dans les classes filles il est `public`.

A mon avis, c'est juste un oubli et il faudrait repasser `renderInput` et `renderStatic` dans toutes les classes filles. Il n'y a pas non plus un gros 'impact', je pense simplement qu'en redéfinissant à `public` la fonction cela rend juste leurs fonctions accessibles à l'extérieur bien qu'il y ait un intérêt à ce qu'elle reste `protected`.
J'attends ton avis @srosset81 car on pourrait en profiter pour tout passer en `protected`.

2021-02-03 07:38 UTC, acheype commented
@J9rem Cool, j'aimerais juste en profiter pour faire un commit ou deux de détails de refacto, j'ai fait attention à bien séparer cette fois ;)
Par contre, je n'ai pas compris ce qu'il s'est passé au niveau de Github, je pensais simplement que vu que tu t'étais rebasé sur la branche de #633, que je pouvais supprimer cette dernière. Mais je n'avais pas vu que cette PR était en fait rattachée à la branche de #633 et la suppression de cette dernière a fermé la PR.
On peut toutefois continuer à discuter ici, et dès que c'est ok on merge `fix-field-acl-forempty-fieldacl`... à moins que vous ayiez une autre proposition.

2021-02-03 07:40 UTC, J9rem commented
@acheype je pense qu'il fallait faire #631 merge vers #633.
Puis passer sur #633 pour faire un merge de #633 sur Doryphore.
En fermant #633, tu fermes en même temps la branche fille #631, .....
Je te laisse réouvrir les branches à ta convenance et faire les commits nécessaire ;-)

2021-02-03 08:05 UTC, acheype commented
oui j'aurais dû faire cela, je n'avais juste pas vu cela de cette manière.

j'ai restauré la branche de #631 mais je ne sais pas comment réouvrir la PR, tu saurais @J9rem ?

2021-02-03 08:28 UTC, oncletom commented
Ce n'est pas possible de réouvrir cette PR (#631) car ses commits sont déjà intégrés à #633 (sa branche de destination).

Le travail doit continuer dans #633.

2021-02-03 13:25 UTC, srosset81 commented on tools/bazar/fields/BazarField.php
> +    protected function renderStatic($entry)
Faudrait regarder le code, j'ai pas le temps-là. Faites au mieux...

2021-02-03 14:14 UTC, acheype commented on tools/bazar/fields/BazarField.php
> +    protected function renderStatic($entry)
ok merci, je vais faire les changements, c'était aussi pour te prévenir.